### ISSUE TITLE
org.openhab.binding.network : Cannot use DHCP listen: Permission denied

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2-addons#1075]
@davidgraeff On Mac OS X Server El Capitan, with the latest build of the above binding, I get the above Error in the logs. The usage of a dhcp listener is a new feature, and it requires augmented permissions (cfr README), but what is the equivalent of 

`setcap 'cap_net_bind_service=+ep' /usr/bin/java`

on Mac OS X?

AFAIK there is none, and maybe therefore a check of the OS needs to be done in the binding and disable the feature on Mac OS X

ps. Should the ERROR not rather be a WARN?
##

**Comment by davidgraeff** [comment]
There should be a mechanism for Mac OS applications to aquire ports < 1024, web development with local webservers, ssh etc wouldn't be possible otherwise. Unfortunately I have no idea, I do not own apple products.

The feature is disabled automatically if the port cannot be aquired, but the error message is correct in my opinion, because the user required the feature explicitly (at least the default configuration is set to "on"). The default can be changed of course, but i expect this feature to be overlooked then.

**Comment by kgoderis** [comment]
@davidgraeff David, the thing-types.xml in the ESH-INF folder is missing the definitions for dhcplisten="true"

**Comment by davidgraeff** [comment]
@kgoderis I'll fix that asap

**Comment by davidgraeff** [comment]
@kaikreuzer This can be closed now, the feature got merged.
