### ISSUE TITLE
Network binding: port parameter lacks clarity

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab2-addons#1156]
@mettke @davidgraeff 

The [Network binding documentation](http://docs.openhab.org/addons/bindings/network/readme.html#thing-configuration) is not clear on the true nature of the `port` parameter. Without further studying the source code I expected it to be an option to probe some random other service for a response (http, ftp, ...), which would be amazing but doesn't seem to be the case. In fact even if I set `port=8000` (my local http server) Online/Offline status is still decided based on ping.

The documentation could use an update and depending on that, I might want to report the described bug.
##

**Comment by davidgraeff** [comment]
Actually the binding should open a tcp connection if a port is set, it's a bug otherwise

**Comment by mettke** [comment]
@ThomDietrich 
Unfortunately I can't see the problem you are describing. As you can see at

https://github.com/eclipse/smarthome/blob/e0985e90d389350580e59bfbcd7e0adaaccf7519/bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/actions/Ping.java

the functionality of Ping is to create a Socket when the Port number is greater than zero. So it should be easily possible to ping a service by doing so.
Using "use_system_ping" however does and will not work with Ports. That is not a bug, because (as the parameter says) it is using the ping of the Operating System which does not accept different ports.

**Comment by ThomDietrich** [comment]
Thanks for the clarification! Let me show you some finding:

```java
//Windows 10 firewall active, port=0, use_system_ping="false"
Firewall blocks the connection, no DEBUG message                              (*1)
//Windows 10 firewall active, port=0, use_system_ping="true"
established connection [host '192.168.0.2' port '0' timeout '5000']           (Good)

//Windows 10 firewall deactivated, port=0, use_system_ping="false"
established connection [host '192.168.0.2' port '0' timeout '5000']           (Good)

//Windows 10 firewall active, port=8888, use_system_ping="false", webserver on PC not active
timed out while connecting to host '192.168.0.2' port '8888' timeout '5000'   (Good) (*3)
//Windows 10 firewall active, port=8888, use_system_ping="false", webserver on PC active
established connection [host '192.168.0.2' port '8888' timeout '5000']        (Good)

//Windows 10 firewall active, port=8888, use_system_ping="true", webserver on PC not active
 established connection [host '192.168.0.2' port '8888' timeout '5000']       (*2)
//Windows 10 firewall active, port=8888, use_system_ping="true", webserver on PC active
established connection [host '192.168.0.2' port '8888' timeout '5000']        (*2)
```

There seem to be some problems:
* In regards to (*1): a debug message is missing
* In regards to (*2): It's not clear that <use_system_ping="false"> overrules the port parameter completely. Wise? Documentation needed! 
* In regards to (*2): Even though ICMP ping is used, the DEBUG message states "port '8888'", which is incorrect
* (In regards to (*3): Square brackets are missing)

-------

Also, sorry for being oldschool here, but don't you think that would be cleaner instead of an "unconditional" `success=true` in the middle of a maybe growing function?

```java
Socket socket = new Socket();
try {
    socket.connect(socketAddress, timeout);
    success = true;
} 
catch (SocketTimeoutException e) {
    throw e;
}
finally {
    socket.close();
}
```

**Comment by davidgraeff** [comment]
I'm travelling right now so cannot commit anything in the near future i suppose. In my opinion a custom Port should Overwrite the system ping setting.

**Comment by ThomDietrich** [comment]
I think so too. In the mean time I've updated the documentation to describe the current state, this can quickly be changed.
Maybe the combination of system ping *and* custom port should even be disencourage by a warning (but still accepted by the algorithm)!?

**Comment by davidgraeff** [comment]
The system ping thing only exists because of the bad internal java implemenation. The user shouldn't be bothered here. I even suggest to not let the user choose between system/java ping. I propose this:

On Startup --> Test if system ping works (by pinging a local address).

Use system ping for default, use the java ping for fallback, use a tcp connection if a port is set.

**Comment by ThomDietrich** [comment]
@davidgraeff (just going through my open issues...) any updates on that matter?

**Comment by ThomDietrich** [comment]
Any news?

**Comment by davidgraeff** [comment]
I'm travelling new Zealand at the moment and can't provide any code or doc updates.

**Comment by ThomDietrich** [comment]
Welcome back, I guess ;) Thanks for looking into this!
