### ISSUE TITLE
The chart renderer doesn't work with the switch item in openhab2

### ISSUE THREAD

**Issue by normen1** [openhab/openhab2-addons#1429]
If you connect a chart in openhab2 with a switch item which has the value on/off a chart doesn't show a graph. If you change the item to an number item with 0 and 1 value the graph will be displayed.

**Comment by kaikreuzer** [comment]
This does not seem to be related to any openhab2 add-on (this is what this repo is about).

From your description, I cannot tell whether there is a bug somewhere in charting, persistence or any UI/app or if it merely is a misconfiguration. I'd suggest that you first discuss your issue at https://community.openhab.org/ and enter an issue at the right repository, once it is clear where the problem is.

**Comment by paveleremin** [comment]
@normen1 did you solve this issue? I also plane show chart for the switch item

**Comment by watou** [comment]
@paveleremin please see https://github.com/eclipse/smarthome/pull/2835
