### ISSUE TITLE
Homematic: DateTime Handling for HMIP-WTH - PARTY_TIME

### ISSUE THREAD

**Issue by kohlsalem** [openhab/openhab2-addons#1445]
Hi,

Homematic IP Thermostats support with their IP AP a very nice "Urlaubsfunktion" Vacation Feature. I can basically lower the heating until a given date/time.

Now i run the IP Thermostat on a ordinary CCU2, and want to reestablish the Feature vis OH2.

i configured items:

Switch PartyMode      "Party Mode" <heating>  { channel="homematic:HMIP-WTH:a8faecaa:000313C98CBC67:1#PARTY_MODE" }
Number PartySetPoint  "Party SetPoint [%.1f °C]" <temperature>  { channel="homematic:HMIP-WTH:a8faecaa:000313C98CBC67:1#PARTY_SET_POINT_TEMPERATURE" }
DateTime PartyTimeStart "Party Start [%1$tA, %1$td.%1$tm.%1$tY %1$tT]" <calendar>   { channel="homematic:HMIP-WTH:a8faecaa:000313C98CBC67:1#PARTY_TIME_START" }
DateTime PartyTimeEnd     "Party End   [%1$tA, %1$td.%1$tm.%1$tY %1$tT]" <calendar>   { channel="homematic:HMIP-WTH:a8faecaa:000313C98CBC67:1#PARTY_TIME_END" }

ViaPaper UI "Control" Section i can see a Value for EndTime "2000_01_01 00:00". However, on OH2 Basic UI, EndTime shows an Err. Even if i remove the Format, i can not see any value. 

So, either i missed a concept, or the Date/Time interpretation of that channels is not working properly...

Thanks
Michael

**Comment by MHerbst** [comment]
I only have the older Thermostats and I tried it with one of them. I did not define an own items file but used the automically created item. 
In PaperUI control section the time is shown as minutes since midnight. I have tried to change the value (not so easy with a slider from 0 to 1410) but it had no effect. Same happened when I tried to set the party start/stop day (setting the temperature worked). Maybe it is only possible to set a complete date with minutes in steps of 30 min.

Seems to be a problem for you @gerrieg

**Comment by gerrieg** [comment]
to say something, i need to see the metadata, because i don't have this device. So please switch the binding into trace mode and send me a full startup log:
```
log:set TRACE org.openhab.binding.homematic
```

**Comment by MHerbst** [comment]
I have attached of my HM-CC-VG-1. Which is the non-IP version of the thermostat.

I think the problem maybe caused because of the special nature of the "Party Times". The settings consists of a combination of 7 values:
- Party Day Start + End
- Party Month Start + End
- Party Time Start + End (which is the value in minutes since midnight in 30 min. steps)
- Party Temperature

I think that the Homematic software checks whether the transmitted values are logically correct that means e.g. that the start date is earlier than the stop date and the time is a multiple of 30. Maybe it is necessary to transfer all values at the same time.

There is also an additional Channel 
![image](https://cloud.githubusercontent.com/assets/616792/20575543/0877a982-b1ba-11e6-8863-73af26b6a361.png)

I think this may be necessary to update the "Party date" information at once. But in the Paper UI it is shown as an editable textfield. 
The best way to configure it would be something like 2 date and time controls with an input field for the temperature and a button to transmit it :-). That's the way the CCU shows it:
![image](https://cloud.githubusercontent.com/assets/616792/20575634/732b8f0a-b1ba-11e6-9cab-68541f07dd33.png)

Maybe it is possible to combine date + time to a single channel and then convert it in the binding to values that can be understood by Homematic. Or don't make these values available at all. I think that the same functionality could be implemented in openHAB with rules that set the temperature directly.

[openhab.zip](https://github.com/openhab/openhab2-addons/files/609783/openhab.zip)

**Comment by kohlsalem** [comment]
[log.txt](https://github.com/openhab/openhab2-addons/files/609839/log.txt)

Attached my trace from the startup. Might it help ;-)

**Comment by gerrieg** [comment]
Yes it helps :-)

PARTY_TIME_START and PARTY_TIME_END are defined as a String and not as DateTime. So you can't use a DateTime item, you have to use a String with a correct String value.

**Comment by kohlsalem** [comment]
Sure, it is a string. And i takes values like "2000_01_01 00:00". But should'nt it be DateTimem looking at the content?

**Comment by gerrieg** [comment]
No, the internal definition of this datapoint in the CCU is a string. It looks like a DateTime, but it isn't.

**Comment by kohlsalem** [comment]
I bet internally in the CCU it is not a sting. Just to the interface it is converted to a string. 

May be my assumption is wrong, but i would expect it it easier to handle dates/times in the appropriate formats than in something i have to build up in a rule. 

Therfore, isn't it easier to convert in the binding than in a rule?

**Comment by kohlsalem** [comment]
Off Topic:
and the longer i think about: The easiest way would be i could leave my HM IP components connected to their AP. All (really well made) convinience in that setup could be preserved. The entire move from AP to the CCU is simply a tinker's nightmare...
But as far as i know does the AP not offer any interfaces to code against. Bad

**Comment by MHerbst** [comment]
@gerrieg for my the non IP heaters the debug messages report the datapoints as single integers:
```
2016-11-28 20:37:20.083 [DEBUG] [o.o.b.h.i.c.HomematicGateway  :570  ] - Received new (Double) value '16.0' for 'MEQ1555808:4#PARTY_TEMPERATURE' from gateway with id '98ad85a9'
2016-11-28 20:37:20.083 [DEBUG] [o.o.b.h.i.c.HomematicGateway  :570  ] - Received new (Integer) value '960' for 'MEQ1555808:4#PARTY_START_TIME' from gateway with id '98ad85a9'
2016-11-28 20:37:20.083 [DEBUG] [o.o.b.h.i.c.HomematicGateway  :570  ] - Received new (Integer) value '29' for 'MEQ1555808:4#PARTY_START_DAY' from gateway with id '98ad85a9'
```

But as wrote before, I think that all PARTY values must be change at once because if you only change one datapoint at a time you may try to set invalid date ranges (e.g. if you set the PARTY_START_MONTH to a higher value than the PARTY_END_MONTH). I have tried to set a single value but it had no effect (there was debug message that the value was sent but without changing the value)

There is also this special datapoint PARTY_MODE_SUBMIT that seems to be related to the other PARTY... datapoints and it seems that this datapoint can be used to set all PARTY_MODE values at the same time. I found this hint in the Homegear forum (in german): https://forum.homegear.eu/t/Partymodesubmit/170

Unfortunately a first quick test was not successful :-(

**Comment by gerrieg** [comment]
I don't know the internal CCU representation, but the CCU says it's a String and therefore i must handle it like a String. Otherwise the binding does not work anymore if the type is changed during a firmware update.
Also see @MHerbst comment, the PARTY_* datapoints have different types for non IP devices.

It's a lot of work to implement all the special cases for all the devices, e.g there is another device with weird handling: [see HM-Dis-EP-WM55](http://homematic-forum.de/forum/viewtopic.php?f=27&t=21710&hilit=HM+Dis+EP+WM55&start=50#p183407)

My recommendation is, do as much as possible in rules and only set the temperature.

**Comment by kohlsalem** [comment]
Why should the fact, that CCU exposes a date/time as a string affect the representation in OH? On the old thermostats its a bunch of numbers. I don not know, if they don't have proper dates or whatever. 

I do know as a user, that date/time as data type is meant to hold date/time entries. I'm aware, every binding speaks a certain protocol to the actual devices. It might transform data as xml, json, bitstrream, csv - i actually do neither know or care. But why should that transport layer format influence the type in OH? 

I do understand, leaving it in strings puts less burden and error sources on the binding. But isn't that a move from the binding to the user?

I thought the entire concept of OH is a bus that normalizes the different interfaces of different things, in order to take burden...

**Comment by MHerbst** [comment]
@kohlsalem I agree with you. It would be desirable to have a normalized and more manufacturer-independent way to work with the different things. But for Homematic with lots of different devices and each with lots of different datapoints this not so easy to achieve. Especially when datapoints of different devices have the same name but different definitions.
The current implementation of the binding creates the channels automatically by reading the datapoint definitions from the CCU. The big advantage of this method is that every device can be used without an individual channel definition and implemention. Also most of the datapoints are absoutely uncritical and would not need an special treatment.
The drawback is that the binding can not implement a special treatment for certain datapoints (like the PARTY....). The CCU returns information about the datapoint types but there are no information about the semantic. E.g. PARTY_TIME is quite strange because it contains the time in minutes since midnight (in 30 min. steps). You can't get this information directly from the CCU.

But I think that it would be possible to combine the automatic channel creation with special device-dependent implementations. I will try to explain my idea: lets's assume that there are only some devices with a limited number of datapoints that need to be handled in a special way (right now I only know about the PARTY... datapoints of the two different heater valves).
Before the binding creates a channel definition, and each time it retrieves values or sets new values it checks whether there is a special handler class available for the respective device. This handler class must be able to provide channel definitions for the device (e.g. by combining datapoints to single channels) and to transform the values that are retrieved or set.
For the heater valve devices the class would combine PART_START_YEAR, _MONTH, _DAY, _TIME to one channel that is defined as a timestamp in a string. When a new value is set it would parse the string and appropriate values for the different datapoints. If the values are retrieved from the CCU is works the other way round.

I am sure whether the description of my idea is understandable enough. What do you think, @gerrieg ?

**Comment by kohlsalem** [comment]
@MHerbst thanks for your explanations about how the binding is implemented! 

Your proposal sounds very reasonable to me.

**Comment by gerrieg** [comment]
It's just like @MHerbst says, there are too many devices and datapoints to analyse and maybe implement a 'normalization'. Many datapoints are also still not documented.
This can be done if the system has only a handful devices to control. My approach was that new devices work automatically.

@MHerbst
Yes, i completely understand your suggestion. I've already implemented something similar, called virtual datapoints. These are datapoints that are added automatically for some devices for special functions. e.g to easier control the 19 button remote control display. Currently this is only one direction: binding -> gateway. This can be expanded to also handle events from the gateway. The advantage is, that the original datapoints are not touched.

I can see how much work that is, but it will take a while.

**Comment by MHerbst** [comment]
Sounds good, @gerrieg . I can help you with the implementation, especially the device-dependent coding and tests e.g. for the heater valve device.

**Comment by mdicke2s** [comment]
@MHerbst was this issue actually addressed within #1521 or any other later change? I was wondering if this issue may be closed...

**Comment by MHerbst** [comment]
@mdicke2s  The datatype of the party mode is now "number", so that has changed. I would close this issue because I think it would be easier (and better) to write a rule in openHAB to set the temperature directly instead of using the "PARTY*" datapoints.

**Comment by mdicke2s** [comment]
ok, thx @MHerbst 
@kohlsalem is that OK for you? could you please close this issue?

**Comment by kohlsalem** [comment]
Well, i changed heating bap to the IP AP, so i can't check.
But from what i read: Yes. Thanks a lot for the changes!
