### ISSUE TITLE
[Squeezebox] support for AudioSink

### ISSUE THREAD

**Issue by airix1** [openhab/openhab2-addons#1630]
Requesting support for AudioSink in the OH2 Squeezebox binding.

see: [https://community.openhab.org/t/openhab-2-squeezebox-text-to-speech/16423/8](https://community.openhab.org/t/openhab-2-squeezebox-text-to-speech/16423/8)

**Comment by mhilbush** [comment]
I'd be willing to take a run at this, although I might need some guidance from @digitaldan or @kaikreuzer.

**Comment by mhilbush** [comment]
Quick status update...  I have something basic working, but the code still needs some work.  It's modeled largely after what was done in OH1.  I'm using VoiceRSS now, but I also have MaryTTS installed.

@kaikreuzer Thanks for setting up that handy cache for VoiceRSS; otherwise, I easily would've exceeded my allotment of 350 calls/day.  👍

I was pulling my hair out for a while because I was getting no output on my piCorePlayer when using MaryTTS.  Switched to VoiceRSS - still not working.  Ack!  Then I tried it with Squeezeplay on my Mac - works.  Tried it with Squeezeplay on a Windows box - works.  Tried it on a Squeezebox Receiver - works.  Tried it on a Squeezebox Boom - works.  Ok, it must be the piCorePlayer.  I'll see if I can open a bug report on that.

**Comment by airix1** [comment]
I'd be happy to test it out if you can post a jar.  
Not sure if related, with my piCorePlayers, and I've had issues in the past with different sample rates depending on what DAC I was using.

**Comment by mhilbush** [comment]
Ok. I hope to have a version at some point next week, assuming I get some time to work on it this weekend. 

I'm still chasing the squeezelite issue on the piCorePlayer. Not sure how quickly that will get resolved. I built an old 1.5 version of squeezelite, and it seems to work on that (at least on an Ubuntu 16.04 workstation).

**Comment by mhilbush** [comment]
Oh, I should've mentioned that I'm seeing the problem with the HiFiBerry DAC+ Light, as well as with the Pi's analog output. I don't think it's the DAC.

**Comment by mhilbush** [comment]
@airix1 If you want to test this, here's a version.  It's not completely done yet, but it's working (for me) with the exception of recent versions of piCorePlayer.  Read the README for how to set it up, as well as current known issues.

https://github.com/mhilbush/squeezebox-test

**Comment by mhilbush** [comment]
@kaikreuzer I failed to mark this fixed in my PR [1684](https://github.com/openhab/openhab2-addons/pull/1684)  

Can you please close this?
