### ISSUE TITLE
All UI spammed by Demo

### ISSUE THREAD

**Issue by Turkburk** [openhab/openhab2-addons#1957]
I've successfully installed OpenHab2 and started it in 'Demo' mode. I wanted to remove it but there is no such option. After some research I find an option to remove by comment out '# package = demo' in file org.openhab.addons.cfg but it doesn't work.

Btw. I would not consider it a 'demo' since it's messing up all the UI and there is no known way to remove.

**Comment by kaikreuzer** [comment]
The demo package create some initial files, which can afterwards be manually customized and used - or deleted. There is no such thing as a "demo mode" that can be activated/deactivated. If you have ideas how to improve this, please dicuss them in the community at http://community.openhab.org/.
Note that this here is the issue tracker for addons only, so I close this issue here.
