### ISSUE TITLE
Openhab 2 Satel Alarm binding

### ISSUE THREAD

**Issue by Nikos78** [openhab/openhab2-addons#2041]
Hello everybody.
My work is Technical Support Manager of Satel alarm systems  for Greece.
I am using Satel alarm binding for openhab  some years now with big success.
Right now I'm testing Satel alarm binding for openhab2 and see it lucks proper support.
Like no auto discovery or even no documentation for custom thing addition.
Any help would be appreciated and also I would be very happy to contribute if pointed the right way, as I'm new to openhab2.
Best regards

**Comment by ThomDietrich** [comment]
Hello @Nikos78,
you have to know, that openHAB 1 bindings can still be used with openHAB 2. The Satel binding is a 1.x binding, hence doesn't know things or auto discovery. In order to support these feature, a openHAB 2 binding needs to be implemented. Everyone is welcome to do so and with your background, you sound like a great candidate ;) The 1.x binding was developed by @druciak, maybe he wants to say something regarding a OH2 version.

**Comment by druciak** [comment]
Hello @Nikos78 
I started working on OH2 version of the binding some time ago, but on that time it was very unstable (OH2) and the api was changing over time so I stopped at some point and decided to wait until it stabilize.
It's good time to start over, but I am working currently on some new feature and once it is finished I will switch to OH2 development. Anyway it will take some time, so for now I would recomend using 1.x on OH2.

**Comment by druciak** [comment]
Also OH2 does not support actions which for me is very important feature so personally I am not going to switch to OH2 now.

**Comment by Nikos78** [comment]
Dear ThomDietrich thanks for your answer! I know it and I'm already using it.
Dear Druciak great news! I couldn't agree more with you for the things you mentioned I'm also using openhab 1.x and OH2 only for testing and development. But cannot overlook some great features of OH2...
If you need any help I'm glad to offer.

**Comment by druciak** [comment]
Just made a #2355. It does not contain all the features OH1 version has, but shuld be functional.
