### ISSUE TITLE
The skeleton script should be updated to include openHAB about.html

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab2-addons#2205]
The skeleton script should be updated to include openHAB about.html

**Comment by cweitkamp** [comment]
Hey Martin,

if you are updating the skeleton script or the templates for creating new bindings there may be optimized some more things. I noticed some facts - just post this to be mentioned and not forgotten, I will add detail information later:

- license header in templates are wrong
- `final static` -> `static final`
- doesn't compile because of tabs in templates

**Comment by martinvw** [comment]
Fair points, I believe I addressed all of them already, please check at: https://github.com/eclipse/smarthome/pull/3278

**Comment by cweitkamp** [comment]
Yes, you did. Thanks. I checked the PR. Only thing to point out is the use of `final static` instead of `static final` in class `__bindingIdCamelCase__HandlerFactory.java`.
