### ISSUE TITLE
RFXCOM Issues with Byron SX Doorbell (Message not supported)

### ISSUE THREAD

**Issue by Res-Hub** [openhab/openhab2-addons#2253]
Hi Guys
I'm trying to get my doorbell working in OpenHab2 using RFXcom binding. 

I'm only getting [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message not supported, data: 07160090000F0270.

Using RFXManger I'm seeing:
Packettype    = Chime
subtype       = Byron SX
Sequence nbr  = 11
ID            = 000F
Sound         = SX21 Solo
Signal level  = 6  -72dBm

Can we look at adding support for this?
Many thanks

**Comment by martinvw** [comment]
Its an relatively easy task, because support was already added to the openHAB version 1 (after the source codes where split). Anyone can create a PR to port the [message class](https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComChimeMessage.java) and related logic to openHAB (2).

Please mention the original author as well by using the `also-by` in your commit message next to your own `signed-off-by`. 

For an example of porting such a message see: https://github.com/openhab/openhab2-addons/commit/149d2e2263305df9b932121adb1fc99c8bba4354

Note that SpeederC also contributed the RFXComChimeMessage so it should look the same.

**Comment by mjagdis** [comment]
And in a jar...
[org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/994492/org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.zip)

**Comment by mjagdis** [comment]
Newer jar with review changes

[org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/994656/org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.zip)

**Comment by martinvw** [comment]
>Newer jar with latest PR changes
>
> org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.zip

@Res-Hub @mjagdis is this newer jar maybe for another issue, I saw no review comments on the chime yet.

**Comment by mjagdis** [comment]
No. I, uh, forgot to plug chime into the handler the first time :-(

**Comment by Res-Hub** [comment]
I have tested the latest SNAPSHOT which works very well no issues.. Many thanks you both @mjagdis and @martinvw for implementing this, Great to have this working now.. Made my day..
Also to note the auto discovery is now working better for the binding than before.. Some devices had to be manually added before but are now auto discovered into the inbox.. Nice work..

Quick question on the same binding but not regarding Byron SX.
Would I need to add a new issue to get some extra from a WIND sensor?
Packettype    = WIND
subtype       = WIND7 - Alecto WS3500,WS4500
Sequence nbr  = 13
ID            = 57345
Direction     = 0 degrees  N
Average speed = 0.8 mtr/sec = 2.88 km/hr = 1.79 mph
Wind gust     = 0.6 mtr/sec = 2.16 km/hr = 1.34 mph
Signal level  = 6  -72dBm
Battery       = OK

I currently only see in OH2 for wind speed (Average wind speed in meters per second) and not the Wind Gust. 
Also for Direction we currently only get the degrees and not N,S,E,W etc.. Could we look at adding this support?

Many thanks for your help guys.

**Comment by martinvw** [comment]
@Res-Hub better just open a new issue for the wind, I believe it is also just a simple port to have at least basic functionality.
