### ISSUE TITLE
[Milight] Connection to iBox at different subnet

### ISSUE THREAD

**Issue by orificer** [openhab/openhab2-addons#2321]
I've tested the Milight Binding (version 2.1.0.201705282306 at the moment) some time at my test environment of openhab and everything was working as expected.

Now I want to move to the production environment and I'm not able to place the (WiFi connected) iBox2 at the same subnet as the RasPi where openhab2 is running. The segmentation between the networks (LAN and WLAN) is done by a FortiGate firewall and I'm able to implement the needed rules, but I think the issue is caused by two different things:

1. The broadcast packets sent for discovery. That isn't really an issue because I'm able to create the new thing for the iBox manually. (I was also able to forward the broadcast-packets to the different subnet and get the reply packets (unicast) back to the openhab instance, but there was no new device at the inbox)

2. The Bridge-ID which is the MAC address of the iBox. Because the iBox is at a different subnet there is no way for openhab to see the MAC address at Layer 2. 

Is there any way I'm missing on how to connect to a Milight bridge at a different subnet or is a change at the binding needed? As far as I understand the documentation at http://www.limitlessled.com/dev/ there is no need to be at the same subnet to be able to send commands to the bridge.

**Comment by davidgraeff** [comment]
Discovery only works in the same subnet, we use broadcast packets. The problem is, that the V6 Bridge needs an established udp based session with a three way handshake and the first packet is again a broadcast packet. I developed the binding, but I'm traveling, so I never had access to a physical Milight V6 bridge. I basically figured out the exact process of the handshake and all not documented protocol features by try and error and with the help of the community. I therefore hesitate to change the session establishing process, it may break the binding for everyone.
