### ISSUE TITLE
[SqueezeBox] not able to login with user/password

### ISSUE THREAD

**Issue by Baumi1245** [openhab/openhab2-addons#2334]
The Squeezebox-binding ist not able to use user/password.

**Comment by michel53** [comment]
I would also like to see this feature

**Comment by michel53** [comment]
See also this topic: [https://community.openhab.org/t/squeezebox-binding-user-password/10255/4](url)

**Comment by mhilbush** [comment]
Sorry for not responding to this sooner.  I've been a bit sidetracked on a few other things.

I took a quick look at this, and it looks like a pretty straightforward change.

I would add two new config parameters to the Squeeze Server thing: userId and password.

- If the userId config parameter doesn't exist, or exists and is empty, the binding will work the way it does today; therefore, the change shouldn't break anyone's existing installation.

- If the userId config parameter exists, the binding will attempt to login to the Squeeze Server using the userId and password config parameters.  

Looks like there may be a few side-effects:

- If the login fails, the binding will try to reconnect and login every 60 seconds.  It does this because the Squeeze Server immediately drops the connection on a failed login, hence there is no way to distinguish between a failed login and some other type of connection issue.  It therefore will not be possible to provide a specific detailed status (e.g. login failure) to go along with the OFFLINE status of the Squeeze Server thing.

- With authentication enabled in the Squeeze Server, during discovery, there is no way to query the server for the CLI port.  Hence, when the binding gets a "401 Unauthorized" response from the Squeeze Server when it tries to query for the CLI port, it will assume authentication is enabled, and just use the default CLI port of 9090.  If you run the CLI on a different port, you will need to manually change it in the Squeeze Server thing config.

If all this sounds reasonable, I can start on the change.

@digitaldan Do you see any issue with this approach?

**Comment by michel53** [comment]
This sounds reasonable, I would appreciate this change! (but I'm not digitaldan...)

**Comment by felixloesch** [comment]
Please implement this. It is needed if you want to control Squeezebox via Alexa as well as for an Alexa Skill the LMS needs to be accessible from the Internet. Of course nobody wants this without having username/password protection enabled in LMS.

**Comment by digitaldan** [comment]
>@digitaldan Do you see any issue with this approach?

Yes, this sounds reasonable!

**Comment by mhilbush** [comment]
Sounds good.  I can make the change later in the week.  I should have something to test on Friday or Saturday.  Anyone want to help test it?

**Comment by Baumi1245** [comment]
> @mhilbush Anyone want to help test it?

of course... hardly waiting

**Comment by mhilbush** [comment]
A version of the binding that supports userid/password authentication to the LMS is here.  Please let me know if you have any questions, or run into trouble.

https://github.com/mhilbush/org.openhab.binding.squeezebox

**Comment by Baumi1245** [comment]
Looks good so far.
After configuration players are found at once.
Testing with SqueezePlayer at the moment - SB-Radio and SB-lite will follow tomorrow.

Thank you very much!

**Comment by mhilbush** [comment]
@digitaldan I submitted the PR for this functionality.  Could you have a look when you get a chance?  Thanks!!

https://github.com/openhab/openhab2-addons/pull/2479
