### ISSUE TITLE
[samsungtv] support without upnp

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab2-addons#2354]
## Expected Behavior

I would expect to be able to add items manually if they are not discovered automatically.

## Current Behavior

My network has upnp disabled, so my tv is not automatically discovered, I assumed that that would not be a problem but my tv remained offline. Now it is off quite often but I put it on for a test now and the item remains offline. Looking at the code it looks like it will only become available after being discovered I saw when looking quickly no way a manual configuration would be picked up if that host was not discovered.

Note that in my old OH1 env it still works perfectly.

## Possible Solution

Fall back to manual connections outside of the discovery mode? So split discovery from actually connecting.

@paulianttila if you agree on my observations I might find some time to work on it, if that is okay with you :-) What would your proposed solution be?

## Your Environment

* Version used: 2.0.0 & 2.1.0-SNAPSHOT
* Environment name and version: docker@Ubuntu / Mac OS

**Comment by paulianttila** [comment]
Hi @martinvw, OH2 Samsung TV binding communication is based on upnp protocol. If Upnp stack is not discovered the TV, binding can't communicate it. OH1 binding doesn't use upnp at all, but Samsung proprietary remote control emulation protocol, which is uni directional like infrared remote control. OH2 bidding also support this, but most of the functionality is based on upnp. 

If you want to just use remote control protocol it probably just easiest to use OH1 binding rather than OH2 binding.

In fact, I made some testing while ago as a like to segregate my media devices to different VLANs. As upnp discovery protocol is based on broadcast, it's difficult to get it work in separated VLANs. In my test, I introduced possibility to manually give uuid's for every upnp device, but communication didn't work as upnp stack didn't had clue about the devices. Most probably, manual uuids work fine if OH and TV is on the same network. If you want to test that approach, give me a moment and I will push those changes to my git repo.

But if you have some clever ideas, please go ahead 👍

**Comment by martinvw** [comment]
I'm not sure whether the ideas I had are clever but it works, if you have time to review and test that would be great :-)

Btw: I discovered that some parts of my network support upnp, but not my wifi and most likely not my docker-instance.
