### ISSUE TITLE
[rfxcom] Intermittent issues receiving data for Owl USB CM160 Energy meter

### ISSUE THREAD

**Issue by Res-Hub** [openhab/openhab2-addons#2360]
Hi Guys

Currently experiencing issues getting data from the above Energy Meter reader.

## Current Behavior
Using the RFXCOM binding I'm not seeing a consistent flow of data around the expected 12secs or so which the Owl 160 Energy display is currently getting. In a day I may see 10 readings. Sometimes within a few mins and other times 3 or more hours in between.

Distance is not the issue between the two devices and they are in the same room 

Debugging this I'm not seeing any issues as such in the way of errors:

/var/log/openhab2/openhab.log.7:2017-06-08 00:26:38.826 [DEBUG] [binding.rfxcom.handler.RFXComHandler] - Received message from bridge: rfxcom:bridge:usbrfx message: Raw data = 115A010504120000000243000000178AFD69, Packet type = ENERGY, Seq number = 5, Sub type = ELEC2, Device Id = 1042, Count = 0, Instant Amps = 2.517391304347826, Total Amp Hours = 29.99248880026468, Signal level = 6, Battery level = 9, Instant Power = 579.0, Total Usage = 6898.272424060877
/var/log/openhab2/openhab.log.7:2017-06-08 03:22:50.754 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 115A016B041204000002130000001E2E6269, Packet type = ENERGY, Seq number = 107, Sub type = ELEC2, Device Id = 1042, Count = 4, Instant Amps = 2.3086956521739133, Total Amp Hours = 38.44929493083437, Signal level = 6, Battery level = 9, Instant Power = 531.0, Total Usage = 8843.337834091904
/var/log/openhab2/openhab.log.7:2017-06-08 03:22:50.754 [DEBUG] [binding.rfxcom.handler.RFXComHandler] - Received message from bridge: rfxcom:bridge:usbrfx message: Raw data = 115A016B041204000002130000001E2E6269, Packet type = ENERGY, Seq number = 107, Sub type = ELEC2, Device Id = 1042, Count = 4, Instant Amps = 2.3086956521739133, Total Amp Hours = 38.44929493083437, Signal level = 6, Battery level = 9, Instant Power = 531.0, Total Usage = 8843.337834091904
/var/log/openhab2/openhab.log.7:2017-06-08 04:42:14.810 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 115A011C0412020000022300000021CFBA69, Packet type = ENERGY, Seq number = 28, Sub type = ELEC2, Device Id = 1042, Count = 2, Instant Amps = 2.378260869565217, Total Amp Hours = 43.074047910724026, Signal level = 6, Battery level = 9, Instant Power = 547.0, Total Usage = 9907.031019466525
/var/log/openhab2/openhab.log.7:2017-06-08 04:42:14.810 [DEBUG] [binding.rfxcom.handler.RFXComHandler] - Received message from bridge: rfxcom:bridge:usbrfx message: Raw data = 115A011C0412020000022300000021CFBA69, Packet type = ENERGY, Seq number = 28, Sub type = ELEC2, Device Id = 1042, Count = 2, Instant Amps = 2.378260869565217, Total Amp Hours = 43.074047910724026, Signal level = 6, Battery level = 9, Instant Power = 547.0, Total Usage = 9907.031019466525
/var/log/openhab2/openhab.log.7:2017-06-08 04:49:14.880 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 115A018B0412020000022300000022078569, Packet type = ENERGY, Seq number = 139, Sub type = ELEC2, Device Id = 1042, Count = 2, Instant Amps = 2.378260869565217, Total Amp Hours = 43.35169404379745, Signal level = 6, Battery level = 9, Instant Power = 547.0, Total Usage = 9970.889630073414

I don't have any other issues in getting regular data from many other RFXCOM devices.
When testing in RFXMgr I receive regular data from the meter reader for the Owl USB CM160. 
So I'm at a lost why the binding is being selective when reporting data to OH2. 
Currently using an RFXCOM SNAPSHOT from issue #2267.

Was also looking into using the USB option on this device instead to get the data from the energy monitor, but this is not working out at the moment due to Linux drivers, so RFXCOM is my only way and should be the simplest way..

Using Ubuntu 16.04 with OH2.

If you need any other info please let me know...

**Comment by mjagdis** [comment]
I have one of these and it seems to work fine. as I understand it they slow the sending rate if the power (amps?) values are close together but certainly not to that extent. Do you have to move it at all to test with RFXMgr? Or even move other things around it (including yourself)? New batteries maybe? Certainly there's nothing in the binding that would drop messages before logging them so if they don't show up the rfxcom isn't receiving them, assuming they are sent at all.

**Comment by mjagdis** [comment]
What protocols do you have enabled and have you saved that as the default or are you letting openHAB enable them on connect?

I was trying to get an old temperature sensor working last night and at some point my OWL started doing exactly the same as yours - just the odd status every few hours. It seems to have started at some point when I was toggling protocols on and off (via the rfxcom thing config in paperUI) and could have been triggered by my enabling Fine Offset, Ruibcson, La Crosse or Undecoded (possibly others...) I can't be sure because I only went to debug when I enabled Undecoded, then I noticed how quiet it was :-(

Even after restoring the rfxcom config to its original state and restarting openHAB my OWL stayed silent. Physically unplugging the rfxcom, waiting 30s then plugging it back in to the server got it seeing regular updates again though.

So it seems that enabling the wrong combination of protocols can cause Oregon Scientific data to not be received (or only rarely received) until the rfxcom is physically power cycled. The rfxcom user manual suggests La Crosse may be the one that broke me. (It also says AD/LightwaveRF blocks Oregon 3.0 which may be why my old temperature sensor doesn't work :-( )

I'm guessing that you set the config via openHAB and that the saved config is different so when you're connected to your openHAB server it doesn't work but when you unplug and move to your Windows PC to debug it magically starts working again...

**Comment by martinvw** [comment]
@Res-Hub any updates of you?

**Comment by J-N-K** [comment]
No feedback for nearly two years, closing. If still an issue, please open a new one.
