### ISSUE TITLE
[MiHome] Smart socket plug not responding to power ON/OFF commands

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab2-addons#2405]
This issue is addressing reports from @xX-Nexus-Xx and @CoolWombat.

See the following comments for reference:
https://github.com/openhab/openhab2-addons/pull/1660#issuecomment-311510707
https://github.com/openhab/openhab2-addons/pull/1660#issuecomment-311512850

Cc; @dimalo @pboos @tavalin

**Comment by CoolWombat** [comment]
@dimalo Not sure if this would help, when I physically turn the switch on and off by pressing on the button on the side of the switch, the state is reflected correctly on the power channel in Paper UI \ Control. However, when I click on the power channel in Paper UI \ Control, the physical switch doesn't change state and I got the java error as listed in the previous posting.

**Comment by dimalo** [comment]
I looked into it and am still not sure whats going wrong.
Will get me a device to test.
Does writing to the gateway work for you guys? Light, sound etc.?

**Comment by CoolWombat** [comment]
@dimalo Now that you mentioned it, I went and tested all my devices and found that the Aqara wall switch 2 buttons is behaving the same like the smart plug ie: when I click on the physical button, the state gets reflected correctly in the Paper Ui \ Control. However when I click on the switch in the Paper UI \ Control, although the icon changes state, the physical switch doesn't change state and I get the java errors. So it seems like all incoming into OpenHAB2 is fine but outgoing to switches are broken.

Writing to Gateway seems to be working, sending brightness and sound all work as before.

**Comment by inakif** [comment]
hi all, this is my first post here.

I have installed oh2 in a raspberrypi and testing with xiaomi devices.

I have the same issue with the xiaomi plug. When I use a xiaomi switch to active/inactive the plug, oh2 paperui shows well the status. But when I apply changes with the oh2 paperui, the plug is not activated.

I have before oh 2.0 and now oh 2.1, but the same issue in the both versions. I don't see any error in openhab logs, so it seems that the command is send correctly from oh2 to the gateway.

I have installed the following binding: org.openhab.binding.mihome-2.1.0-SNAPSHOT.jar

The rest of the gateway writting is working well: set sound, set bright and colors

thanks and regards,

**Comment by inakif** [comment]
Hi guys,

I have fixed the issue with this change on the mihome binding code.

File: XiaomiActorPlugHandler.java

getXiaomiBridgeHandler().writeToDevice(itemId, new String[] { "status" }, new Object[] { status });
==> 
getXiaomiBridgeHandler().writeToDevice(getItemId(), new String[] { "status" }, new Object[] { status });

The issue was that the itemId was not initialized in this class, or at least it is twice defined in this class and also on the inherited one called XiaomiDeviceBaseHandler.

I have made this change, compile and install again, and after it worked. I need to tell that I had some issues with an encrypted key that it is supposed to be sent by the gateway and the switch command was not working, but after some minutes looking to the issue and without touching anything, the switch command works using oh2 and PaperUI, or using the mobile App of oh2.

Hope that helps and that anyone can include the fix on the binding.

regards,
iñaki

**Comment by CoolWombat** [comment]
@inakif If you're right, that also explains why my Aqara wall switch 2 buttons is also not working as both XiaomiAqaraWallSwitch1.java and XiaomiAqaraWallSwitch2.java have similar code -
```
getXiaomiBridgeHandler().writeToDevice(itemId, new String[] { "channel_0" }, new Object[] { status });
```
I'm a noob at this, so have got no idea how to get it fixed in https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/handler/XiaomiActorWallSwitch2.java
and then recompile to get the final .jar file to test this out. I normally get the latest file from here - https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.mihome/2.2.0-SNAPSHOT/
