### ISSUE TITLE
Basicui sitemap Group required `item` argument to be passed

### ISSUE THREAD

**Issue by av1024** [openhab/openhab2-addons#2523]
## Expected Behavior
Define simple 'Group' in sitemap as menu separator (not linked to any `item`)

## Current Behavior
Got "It seems like you have not defined any sitemaps yet." on web UI.

## Possible Solution
 * Pass 'item=' argument to Group
 * Change sitemaps documentation (remove optional brackets from 'item' on Group description)

## Steps to Reproduce (for Bugs)
1. (default.sitemap): ... Group label="test" item=SomePossibleInvalidItem { ... }
2. Remove 'item=' definition and reload web page

## Your Environment
* Version used: openhab 2.1.0 release
* Environment : Pine64, OpenJDK Runtime Environment (Zulu Embedded 8.20.0.42-linux-aarch32hf) (build 1.8.0_121-b42)
* Operating System and version: headless Armbian Jessie 16.04.2/aarch64

**Comment by kaikreuzer** [comment]
Please note that this is the wrong issue tracker as your issue is not about any openhab add-on that is maintained in this repo.
Anyhow, you're problem is not a bug, but an invalid sitemap. Providing an item is mandatory so your second suggestion is the correct solution - I have created https://github.com/openhab/openhab-docs/pull/470/files for it. Thanks for mentioning!

**Comment by av1024** [comment]
Ok.
I'm a bit confused because it is worked on OH1 and looks a bit useful than defining fake item dor dummy group.

**Comment by kaikreuzer** [comment]
Instead of a fake item, you should simply use a "Text" widget instead of a "Group" - or is there any drawback with that?

**Comment by av1024** [comment]
Ha! Worked, thanks!

OH1 has exactly reverse logic - I used "Text" item instead of group to display value.
