### ISSUE TITLE
[network] Compile error: deactivate() method of BaseThingHandlerFactory is illegally called with null

### ISSUE THREAD

**Issue by pfink** [openhab/openhab2-addons#2735]
openhab2-addons build currently fails because network binding is not compliant with the ESH API. Error message

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.0.0:compile (default-compile) on project org.openhab.binding.network: Compilation failure: Compilation failure:
[ERROR] /scratch/jenkins/workspace/sandbox-openhab2-release/openhab2-addons/addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkHandlerFactory.java:[48]
[ERROR] super.deactivate(null);
[ERROR] ^^^^
[ERROR] Null type mismatch: required '@NonNull ComponentContext' but the provided value is null
[ERROR] 8 problems (1 error, 7 warnings)
```
Source code link: https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkHandlerFactory.java#L48

Calling deactivate() with argument null is prohibited which is also enforced since last week: https://github.com/eclipse/smarthome/commit/8d1b12d5fb8e09f9122a49ae0a7c9ba8ca3ade8b

@davidgraeff: Could you take a look?

**Comment by philomatic** [comment]
I wrote a pr which can close this, using same way as other bindings:

https://github.com/openhab/openhab2-addons/pull/2747

@davidgraeff: Can you please say if this is ok for network?

Unfortunately, Jenkins and Travis are failing due to some internal mirror problems, don't know how to solve them :/
Is there a way for me to retrigger the build?

@kaikreuzer Could you please take a look?
