### ISSUE TITLE
[onkyo] Add support for TX-NR676E

### ISSUE THREAD

**Issue by DanNielsen** [openhab/openhab2-addons#2888]
Please Update Onkyo binding with Onkyo TX-NR676E
Almost the same as TX-NR646 but with built in Mirrocast.

**Comment by Ontrackx** [comment]
Onkyo TX-RZ720 B please

I can help if wanted (the current bindig works kinda, but some missing inputs)

**Comment by Cossey** [comment]
It seems like support for 676 was added recently, but not for the E model. I can go ahead and get this added in however @DanNielsen I’ll need you to test to make sure it works before I’ll be able to do a pull request. 

@Ontrackx you should open a new issue instead of posting under this one. Just curious to know, what inputs are missing exactly? I know in Basic UI and Habpanel you can specify the choices this channel has. The inputs are identified by two character hex and there’s a list on the readme page. The input channel can change to any input that is supported on the receiver in this way, you just need to know the code for it.

**Comment by cweitkamp** [comment]
No response from both users. Please reopen if this is still a requested feature and ping @Cossey as he is willing to help you.
