### ISSUE TITLE
[Nest] Nest API error: Invalid value: 'autoaway'. Only 'home' and 'away' are permitted values.

### ISSUE THREAD

**Issue by tavalin** [openhab/openhab2-addons#3017]
The 'Away' channel has 3 selection options - 'Home', 'Away' and 'Auto Away.' 

Selecting the 'Auto Away' option results in the following warning in the logs:

`Nest API error: Invalid value: 'autoaway'. Only 'home' and 'away' are permitted `values.``

I presume the options for this channel need amending to reflect this.

**Comment by martinvw** [comment]
CC: @wborn 

That is a though one AFAIK the API can return `auto-away` but you are not allowed to send it. Which is not trivial to handle in openHAB. 

But it seems that it is also deprecated and not supported by any of the newer thermostats: https://nestdevelopers.io/t/api-auto-away-state-deprecation/344/18

PS: I think we also missed a dash...

**Comment by wborn** [comment]
Maybe we should just remove auto-away:
* It's deprecated like @martinvw already mentioned
* When you set this state in the [Nest Home Simulator](https://developers.nest.com/documentation/cloud/home-simulator) the binding receives "away" as state
* It's no longer mentioned in the [API explorer](https://developers.nest.com/documentation/api-reference) when you check the possible values of the away property of a structure
* Its no longer mentioned in the [Home and Away](https://developers.nest.com/documentation/cloud/away-guide#home_and_away) documentation
* All thermostats should have been updated to the new firmware because 1 year has passed since deprecation. If not, they will be when they connect with Nest which is required for using the API

**Comment by martinvw** [comment]
Agreed
