### ISSUE TITLE
[Milight] Night mode issues (flash on activate, won't come out of night mode)

### ISSUE THREAD

**Issue by xnhil** [openhab/openhab2-addons#3398]
With night mode, the light will flash on at what ever it's brightness was, if the light was off before going into night mode. In addition, it sometimes won't come out of night mode (power on command needs to be sent before it'll respond to any other commands).

  I've actually fixed these in my own fork @ https://github.com/xnhil/openhab2-addons/tree/2.2.x_milight But I'm new to GitHub and OH development so I'm not sure of the process for getting this incorporated/reviewed.

  Any feedback welcome :)

**Comment by wborn** [comment]
Bug fixes are always welcome @xnhil! Do you know if this also an issue in the 2.3.0-SNAPSHOT version since your fix is based on 2.2.x? 

We have some [documentation](https://docs.openhab.org/developers/contributing/contributing#pull-requests-are-always-welcome) on how to contribute.

There is already a MiLight PR waiting in which a lot of variables are renamed  https://github.com/openhab/openhab2-addons/pull/3306 . So it is best to wait for that one to get merged to prevent unnecessary merge conflicts.

@davidgraeff is also planning to commit fixes for MiLight issues. Do these also fix this issue?

**Comment by xnhil** [comment]
Hi,
Based on a quick look 2.3 should be affected too, I just used 2.2 as a base since I needed the JAR to fix my OH server.

re: other PR/fixes, I don't think this will be affected by them, but I'm happy to wait till they're merged and I've got them applied to current snapshot version. Skimming the documentation, there's a couple of steps I should probably do get acquainted with to...

re: @davidgraeff commit's, as best I can tell this isn't related, though I did need to duplicate #3093 ESH change to re-enable the whitemode and nightmode actions. So, yeah, will probably need to bring my fork up to date to limit merge issues :)

  Thanks,

**Comment by cooltom** [comment]
Hi guys. Seems like OH still not include this nice fix into official milight addon. And flash before nightmode or infront of any scene start with 0 brithness is crazy ... Can I ask you share compiled JAR file for this milight addon with your correction, please? I can edit / apply your fix on actual source files, but i am just not able compile it into final JAR. Thnx a lot.

**Comment by davidgraeff** [comment]
What kind of bulbs are affected? Is it the new V6 bridge or the older V3 bridge?
