### ISSUE TITLE
[Nest] Add channels for Camera Aware API calls

### ISSUE THREAD

**Issue by rzwarts74** [openhab/openhab2-addons#3458]
## Expected Behavior

I was expecting the Nest Aware API calls for Nest Camera to also be in the code, but unfortunately they are not. I hope there are plans to add those to the Nest Camera Thing as channels.

## Current Behavior

Currently the channels for:
```
• last_event/image_url
• last_event/animated_image_url
• last_event/activity_zone_ids

```
are not available as they are subscription based API calls. This should not be a reason to exclude them (in my view)

## Possible Solution

Add the missing API calls as channels to the Nest Camera

## Your Environment

* Openhab 2.2.0 and Nest 2.2.0 Binding
* Mac Mini MacOS Sierra

I have a Nest Thermostat, Cam and Protect.

**Comment by wborn** [comment]
The binding already has this data. We just need to add some channels to the camera thing for making it available.

Because the [last_event](https://developers.nest.com/documentation/cloud/api-camera#last_event) has 11 properties it would be nice to group them all inside a channel group. Though we would then have to move all remaining properties to an additional channel group. That is because a thing can not have direct channels and channel groups (see [documentation](https://www.eclipse.org/smarthome/documentation/development/bindings/thing-definition.html#channel-groups)). :-(

It's best to get https://github.com/openhab/openhab2-addons/pull/3150 merged first to prevent merge conflicts.

**Comment by rzwarts74** [comment]
I just that #3150 was merged. Good news.

**Comment by rzwarts74** [comment]
@wborn how far away are we from integrating everything? Any other open issues ?

**Comment by wborn** [comment]
I had a look if it's possible to mix direct channels and channel groups. The documentation is right and it's not possible. So I think it's better to start using channel groups with Nest camera things, because the last event would add 11 new channels :astonished::

![last-event](https://user-images.githubusercontent.com/12213581/38713131-edcf6e7c-3ecf-11e8-8479-111592fe330a.png)

All these channels would be advanced so you would just see the 3 basic channels you see nowadays unless you click "Show More". :smile: Maybe I have some time to work on it next week.
