### ISSUE TITLE
[Nest] Error after update to build 1271

### ISSUE THREAD

**Issue by vzorglub** [openhab/openhab2-addons#3545]
Every few minutes in the log I get the following error:

2018-05-05 20:57:59.281 [ERROR] [g.nest.handler.NestThermostatHandler] - Unsupported channelId 'time_to_target_mins'

Version used: 2.3#1271
Ubuntu 16.04LTS

**Comment by wborn** [comment]
Recently the channel got renamed in https://github.com/openhab/openhab2-addons/pull/3537 to `time_to_target` because the channel state now has a unit. See also the [[DRAFT] openHAB 2.3 Release Notes](https://github.com/openhab/openhab-distro/wiki/%5BDRAFT%5D-openHAB-2.3-Release-Notes#nest-binding).

You will probably need to delete and readd the respective Thing because Thing Type changes are currently not automatically applied to existing Things.

**Comment by vzorglub** [comment]
Yes, thank you that sorted it.
