### ISSUE TITLE
Usage of @since tags in JavaDocs

### ISSUE THREAD

**Issue by wborn** [openhab/openhab2-addons#3815]
There are 195 JavaDocs with a `@since` tag in the openhab2-addons repository. AFAIK we completely stopped using these for OH2 addons.

Should we just remove these from all OH2 JavaDocs or add a note about how to (not) use these anymore in the [Coding Guidelines](https://www.openhab.org/docs/developer/development/guidelines.html) @kaikreuzer? The coding guidelines also apply to the openhab1-addons repository where these might still be in use and much more common (2949 occurrences).

If they are not removed, they may again get added in new addon contributions or files in bindings that already have these.

The irtrans binding for instance has `@since 2.3.0` tags added to JavaDocs.
They are also not used in ESH except for the [XmlRpcResponse](https://github.com/eclipse/smarthome/blob/2b5a5d179f48b4a8ef646417a00abede85c7039d/extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/internal/communicator/message/XmlRpcResponse.java#L74) class of the Homematic binding. ;-)

**Comment by kaikreuzer** [comment]
I'm ok to remove them in openhab2-addons, but I'd leave them in openhab1-addons since it used to be part of the coding guidelines in the past.
I wouldn't necessarily include anything about it in the coding guidelines as we rather state there what to do and not what not to do (otherwise the list might get far too long ;-)).

I fixed the XmlRpcResponse with https://github.com/eclipse/smarthome/pull/6032 - that's a good example, why the "since" tag can cause confusion when being used :-)
