### ISSUE TITLE
Failed downloading Marketplace entries: Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by HerzScheisse** [openhab/openhab2-addons#4013]
2018-09-24 09:34:33.872 [WARN ] [arketplace.internal.MarketplaceProxy] - Failed downloading Marketplace entries:  : Received fatal alert: handshake_failure
2018-09-24 09:34:33.880 [WARN ] [arketplace.internal.MarketplaceProxy] - Retrying again in a minute

there is a solution in the forum https://community.openhab.org/t/failed-downloading-marketplace-entries-received-fatal-alert-handshake-failure/52045

But this is not working for me on my openhabian....

Will there be a general fix available for all openhab users?

running on a RasPi2 with openhabian latest snapshot

**Comment by martinvw** [comment]
@kaikreuzer do you know whether they switched there certificate or something?

**Comment by kaikreuzer** [comment]
Not aware of any change and the certificate looks valid and untouched.
I can reproduce the issue though, so this needs to be analysed.

**Comment by martinvw** [comment]
Where does the marketplace integration live, ie what would be the proper place to have this ticket?

**Comment by kaikreuzer** [comment]
https://github.com/eclipse/smarthome/tree/master/extensions/extensionservice/org.eclipse.smarthome.extensionservice.marketplace

But I don't think that anything can be done in the code really. As the solution in the forum shows, the problem is an unsupported (strong) cypher, so the JRE needs to be adapted in that case.
According to https://bugs.java.com/view_bug.do?bug_id=JDK-8170157, Oracle JVMs since 8u161 should actually work.

**Comment by martinvw** [comment]
FTR, for docker contains this can be configured using:

```
    environment:
      - CRYPTO_POLICY=unlimited
```

https://github.com/openhab/openhab-docker#java-cryptographic-strength-policy

**Comment by martinvw** [comment]
Let's continue the specific openhabian measures in https://github.com/openhab/openhabian/issues/447
