### ISSUE TITLE
[modbus] Test failures

### ISSUE THREAD

**Issue by wborn** [openhab/openhab2-addons#4123]
The tests still seem to fail @ssalonen, see the last [Jenkins build log](https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/org.openhab.io$org.openhab.io.transport.modbus.test/427/testReport/org.openhab.io.transport.modbus.test/SmokeTest/testUnregisterPolling/).

```
Error Message
Measured avarage poll period 687.500000 ms (3 responses in 1375 ms) is not withing expected limits [190, 600]

Stacktrace
java.lang.AssertionError: Measured avarage poll period 687.500000 ms (3 responses in 1375 ms) is not withing expected limits [190, 600]
	at org.openhab.io.transport.modbus.test.SmokeTest.assertPollDetails(SmokeTest.java:755)
	at org.openhab.io.transport.modbus.test.SmokeTest.testUnregisterPolling(SmokeTest.java:804)
```

**Comment by ssalonen** [comment]
So sorry that this is causing trouble.

Since these tests test the timing, it looks like occasional slugginesh is causing us trouble. Looks like previous improvements in #4057 was not enough to remedy all issues. 

I have couple of proposals going forward
1. disabling timing assertions  in Jenkins (would be detected by env variable `JENKINS_HOME`)
2. increase the number of requests in the tests, test would last approximately `num_requests * poll_period`. I think this should reduce the variance to random slugginesh but has the downside of slow tests. Currently poll period is 150 - 200 ms (depending on test case) and number of requests is 3-5.

I am proposing option 1. This would have the benefit of developers running the tests locally but leaving common CI more robust.

Any comments?

**Comment by wborn** [comment]
I don't know what these tests do. Personally I never run tests on build servers that expect code to be executed within 2 seconds or less. If these machines are shared with a lot of users or a lot of garbage collection occurs, execution can stall for several seconds.

**Comment by ssalonen** [comment]
Indeed, I think this is what is happening here as well.

The tests are setting a regular poll using modbus transport bundle API, and then confirming that rate of poll is matching roughly the poll rate that was requested.

The actual poll rate is measured based on some 5 requests, and requested poll rate is some 200 ms. You can see the tolerance we allowed in the assertion message... In this case we accept even rate of 600 ms.

I can see now that this sensitive tests are not suitable here. I would not want to make them any longer either so I would propose we disable the timing tests in Jenkins.

Waiting for your comments, though, before proceeding.

**Comment by wborn** [comment]
Perhaps you can use [JUnit Categories](https://github.com/junit-team/junit4/wiki/categories) and exclude these tests by default? 

I think the systeminfo binding tests also uses categories. But if I remember correctly it didn't work properly because the "slow" tests still run. :-/

Also keep in mind that Travis also runs all tests.

**Comment by ssalonen** [comment]
PR submitted. I decided to use `Assume` instead of Categories, to disable just part of the assertion in the tests.
