### ISSUE TITLE
mDNS floods network

### ISSUE THREAD

**Issue by rage1337** [openhab/openhab2-addons#4154]
## Expected Behavior
Service discovery does not impact network.

## Current Behavior
Every 15 seconds my network breaks down. I could narrow it down to openHAB. The effect does not occur when openHAB is deactivated.

[Network throughput](https://ibb.co/g8eei0) - Graph of the network throughput while the problem occurs.

Every 15 seconds, the network becomes unusable. It makes no difference if the openHAB box is in the WIFI or the cabled network.

I scanned the network via Wireshark. On every breakdown, the network is flooded with mDNS data. See [picture attached](https://ibb.co/hdH5dA) .
- 192.168.12.37 -> RPi3 with openHAB
- 192.168.12.24 -> Macbook I'm currently using

## Steps to Reproduce (for Bugs)
1. Setup Raspbian
2. Install openHAB
3. Configure Sitemap
4. Configure Items Groups
4.1 (no flooding until now)
5. Install binding (doesn't matter which one, I started with Alexa, Bluetooth)
5.2 Flooding starts after a few seconds

## Your Environment
* Version used: 2.4.0-SNAPSHOT
* Operating System and version):Raspbian 9.4 on RPi 3

## Misc
While scanning the Wireshark data, I realized the Icloud-Binding was scanning - I never installed this one. 

I'm not sure which data to provide to be useful.

**Comment by rage1337** [comment]
New Information:

The problem only occurs, when Paper UI is active. After removing PaperUI, the network is stable.
Also, the mDNS queries stop.

Is there any background discovery within PaperUI with an interval of about 15 seconds? I was unable to find anything in the documentation and/or the the configuration files.

**Comment by rage1337** [comment]
New Information:

The problem only occurs, when Paper UI AND the bluetooth binding (openhab-binding-bluetooth 2.4.0-SNAPSHOT) are active. 
Steps to reproduce:

- Setup the system
- Launch Paper-UI
- Install Bluetooth Binding 
- Flooding starts
- Uninstall Bluetooth Binding
- Restart openHAB2 service
- No more flooding

**Comment by rzwarts74** [comment]
mDNS is a basic network function of modern networks to discover services like Chromecast, Homekit, Philips Hue etc... A network should not break because of this (and it's actually weird that you just get this when you start OpenHAB, but I am not familiar with RasPi. 

I have mDNS running on 20 devices (without openHAB) and no issues. So this is really not openHAB related. It just shows that there already is an issue in the setup.

**Comment by wborn** [comment]
If this is a software issue it should either be reported in the:
* [jmdns issue tracker](https://github.com/jmdns/jmdns), where the jmDNS library source code is maintained
* [Eclipse SmartHome issue tracker](https://github.com/eclipse/smarthome/issues), where the jmDNS library is used to provide discovery results to `MDNSDiscoveryParticipant`s such as the openhab2-addons

The bindings in the openhab2-addons repo just listen to the results provided by ESH. Perhaps enabling debug logging can help finding the root cause?
