### ISSUE TITLE
Telegram sending picture

### ISSUE THREAD

**Issue by djuscha** [openhab/openhab2-addons#4286]
From externally one can send so the picture by Telegram

sendTelegramPhoto(“Openhabbot”,“http://www.selfhost.eu/msubmenu=jpg”,null, “admin”, “pass”)

How is the code when I have the image in the tmp directory of Raspi /tmp/1.jpg?

**Comment by AngelosF** [comment]
Use the [community forum](https://community.openhab.org/c/add-ons/actions) for such configuration assistance type of questions please
Github is mainly for Bugs, Feature requests, etc

**Comment by wborn** [comment]
I had a look at the code and it looks like you can use a file instead of an http URL: 

`file:///your/file/here`

Please use the community forum next time for support questions.

**Comment by mhilbush** [comment]
Hmm. When I tested this the other day, it appeared that HttpClient doesn't support the file:// protocol.

https://github.com/openhab/openhab1-addons/issues/5713

**Comment by wborn** [comment]
After closer inspection I think you're right @mhilbush! The code is just confusing because the `photoURL` parameter is also used for the base64 data. :cry: So if you want to get it added you could create an issue (or PR) for this in the [openhab1-addons issue tracker](https://github.com/openhab/openhab1-addons/issues) @djuscha .

**Comment by mhilbush** [comment]
I wish it was that easy. 😉 

The other day I actually made the change in the Telegram action to test it (added a test for photoURL=="file" to the check [here](https://github.com/openhab/openhab1-addons/blob/master/bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/Telegram.java#L186)).

Unfortunately, it fails [here ](https://github.com/openhab/openhab1-addons/blob/master/bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/Telegram.java#L203)because the underlying library (HttpClient) doesn't support the file protocol. :-o

https://stackoverflow.com/questions/33256117/apache-httpclient-get-file-from-local-filesystem

**Comment by AngelosF** [comment]
btw, I gave a "workaround" to the OP here: https://community.openhab.org/t/send-pic-telegram/58021/2

**Comment by mhilbush** [comment]
I saw that post! It inspired me to put a sym link to the local images directory in `conf/html`. I used a sym link because the images directory is very large, and I wanted to keep my openHAB backups small. 😄

**Comment by wborn** [comment]
Maybe just add something like:

```java
        } else if (photoURL.toLowerCase().startsWith("file")) {
            image = Files.readAllBytes(Paths.get(new URL(photoURL).toURI()));
        } else {
            // Load image from provided base64 image
            ...
```

**Comment by mhilbush** [comment]
@wborn Thanks for pointing out the way to do this. I had completely overlooked this approach.

I'll submit a PR to add support for the file:// protocol as soon as I get some issues sorted out with my IDE. ☹️
