### ISSUE TITLE
[Hue Emulation] all devices shown as type Dimmable Light by discover API

### ISSUE THREAD

**Issue by ggggh** [openhab/openhab2-addons#4321]
Hue Emulation API (discover.xml) is showing all exposed devices as "type":"Dimmable Light".
This causes some errors later in Alexa.
Issue described here: https://community.openhab.org/t/hue-emulation-exposes-all-devices-as-dimmable-alexa-complains/42740

May be a configuration issue (wrong syntax somewhere?), but I don't seem to be the only one with it, so might require some documentation update.

Upon getting errors from Alexa, investigated and found the issue seems to be that all of the devices are listed as type dimmable light, hence return values are not just on or off.
This can be seen in http://[openhab_server_ip]/api/discover.xml

Version used: Raspbian with Openhab 2.3, Hue Emulation 2.3

**Comment by Kaskadeur111** [comment]
Hi, i was very pleased and desperately waiting for Hue-Emulation updates (colored bulbs etc.) but now i am disappointed and even more important i am totaly Stuck in upgrading Openhab 2.4.0 Snapshot (1302) to the official Release, mostly because of Hueemulation (which is the main Thing of controlling my home via Alexa).

After 2 Weeks of trying to get it to work i am almost at the point to throw it all away. The Old hue emulation worked like a charme, the new one brings me to tears...

1) I run a Synology Docker installation ... i needed 2 days to get my Docker to reroute Port 80 to 8080 automatically... otherwise noe of my 5 Alexa found the Hueemulation Bridge/Items --- WHY? The old Hueemulation didnt need port 80 at all ?!? (seriously, please Answer this Question, so i can understand it) I cant believe in "Some echos of 2nd Gerneation just look at port 80".

2) After finding The Items via Alexa (needed another forth and back testing Days) I experienced the folowing: I have "Switch" Items which aren't bound to a channel (They trigger Rules if the receive the Command "OFF" or "ON"). They are Tagged as ["Switchable"]

Hue Emulation exposes them as "Royal Philips Electronics intelligentes Gerät"  So far so good. BUT: These items are stated as "OFF" in the Alexa App (which is correct, since they are not bound to any device) .. Problem is: If i sy "Alexa schalte ITEMNAME aus" they dont get the "OFF" command and my rules dont fire anymore.

If i Tag these Items as ["Lighting"] they are exposed as "Dimmable Lights" and behave the Same... If they are of they dont get The "Off" Command from Alexa anymore.

I tested with the Old Hue Emulation: Switches are exposed as "Lux Light" and receive "OFF" commands from Alexa regardless of their state before.

I think i need the "Lux Light" Item Type. Maybe it is possible to make this configurable (Expose Switchable items as ... Dropdown "Lux Light , Royal Philips Electronics intelligentes Gerät"). Just a thought.

I have more complaints about the new Hue Emulation, but the second point is the Key function i cant live without.

I badly need the Update to Openhab 2.4.0 because the MQTT1 Binding is not reliable at all, but i need Hueemulation too.

Greetings Jens

**Comment by davidgraeff** [comment]
> If i sy "Alexa schalte ITEMNAME aus" they dont get the "OFF" command and my rules dont fire anymore.

That was fixed like two days ago. The binding is very strict in multiple aspects to bring it close to a real hue bridge and it didn't send an update to an item if the item had that state already. After the fix it will now send the state no matter what.

**Comment by Kaskadeur111** [comment]
**Thanks, great news. I tested this and it works! Nice... But

another (more critical) error shows up :-(
now all(!) "Color" items WITHOUT Tag are discovered aswell, and that leads to wrong/misleading item control (i say "Esstisch aus" and the item "Licht Küche" gets the OFF command. Maybe a wrong internal id because of the untagged discovered items?

Example Item without Tag (I dont add items in PaperUI, all Textfile based):
Color  wifiled_kueche_links_farbe              "Kueche links Farbe"             <colorwheel>                                                      {channel="wifiled:wifiled:A020A613AF11:color" }

please help. :-)**

**Comment by davidgraeff** [comment]
> After deleting every single Device via alexa.amazon.com

Yes I experienced the same. I switched multiple times from a first gen hue bridge to a second gen hue bridge to Deconz. And every time this bug hits me in my face. Should be mentioned in the Deconz troubleshooting section. Although I don't know if we should feel responsible for Amazon programming faults.
