### ISSUE TITLE
[modbus] serial stopBits parameter value

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab2-addons#4403]
This is PROBABLY a docs issue? but determining that is above my pay grade.

Modbus serial Bridge parameter stopBits requires a string, in reality one of 1, 1.5, or 2
Setting "1" in a xx.things file displays a blank in Paper UI, when reviewing settings - the listed options there are "1.0" etc. and so do not match.
"1" actually functions but gives the appearance of error I believe.
See forum post
https://community.openhab.org/t/solved-modbus-binding-v2-serial-problems/60070/7

A quick fix would be to amend docs to advise options as "1.0", "1.5" or "2.0" for xx.things file users.  

An alternative would be to rework the PaperUI options list to handle "1" and "2"

**Comment by Rossko57** [comment]
I'll add that Modbus requires heavy manual lifting from the users, it's the nature of the beast.  It is not unreasonable to expect them to follow configurations docs carefully - so my vote is for a docs only chnage recommending "1.0"

**Comment by ssalonen** [comment]
Agree about fixing the docs, it's an obvious issue since even Paper UI "values" have the decimal format (https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.modbus/ESH-INF/thing/bridge-serial.xml)

Of course if it would be possible to map many values to same label in Paper UI (case #4148), that would be great. Here we would treat "1.0" and "1" the same...

**Comment by Rossko57** [comment]
Okay, tried
https://github.com/openhab/openhab2-addons/compare/master...Rossko57:patch-1

**Comment by Rossko57** [comment]
This can be closed - live docs currently suggest stopBits values "1.0", "1.5", "2.0"
