### ISSUE TITLE
[onkyo] Add support for TX-NR474

### ISSUE THREAD

**Issue by AlexKay88** [openhab/openhab2-addons#4489]
I would be glad if I could help to get TX-NR474 to be a supported device. I hope it might be quite easy as TX-NR555 and TX-NR575E are very similar to TX-NR474.
I am willing to collect config data, logs or debug logs - whatever you need.
Many thanks in advance!

**Comment by cweitkamp** [comment]
If they are very similar, do you think you can provide a PR on your own (see #4118 for how it is working)?

**Comment by Cossey** [comment]
Alex, I could do this for you (I have recently just added support for my receiver) but I will need you to do a few things, if you don't mind:

* confirm that this receiver **does not** have any Zone Support (ie: Zone 2/Zone 3)
* test the `albumArt` channel with the currently available add-on and see if it correctly displays the album art on Paper UI (this is in regards to push request 4502 of mine) _you will need to play something over the NET input that displays album art (ie: AirPlay or Spotify Connect)_ 
* test the add on that I will build and link to, to make sure it works and detects the receiver correctly _you will need to know how to do this but this is explained in the openHab docs_

**Comment by AlexKay88** [comment]
Hi Stewart,
thanks for your help! I would be glad to test a new addon!

- I can confirm that TX-NR474 doesn't have any Zone 2 or similar

I tested albumArt channel by playing some amazon music and some music with DLNA/UPnP:

- albumArt and albumArtUrl are properly changed as you can see from events.log

Unfortunately PaperUI doesn't show albumArt image: 
![image](https://user-images.githubusercontent.com/22791283/50960156-fcdd0700-14c4-11e9-9e5c-0a5be231bc20.png) (broken image?)
But opening albumArtUrl in a browser always shows albumArt image!

Things:

`Bridge onkyo:onkyoUnsupported:b0e567c4-xxx "Receiver (TX-NR474)" @ "Wohnz" [ipAddress="192.168.xxx.yyy", port=60128, refreshInterval=30, volumeLimit=65]
`

Items:

`Image  Receiver_Image "Receiver Image" { channel="onkyo:onkyoUnsupported:b0e567c4-xxx:player#albumArt" }
`
`String Receiver_ImageURL "Receiver ImageURL [%s]" { channel="onkyo:onkyoUnsupported:b0e567c4-xxx:player#albumArtUrl" }
`

Sitemap:

`Image url="http://192.168.xx.yyy/album_art.cgi" refresh=5000  // works fine!
`

`Image item=Receiver_Image  // does not show image!
`

events.log:

`.ItemStateChangedEvent] - Receiver_Title changed from 100 Suns (00:01:58) to 100 Suns
.ItemStateChangedEvent] - Receiver_Artist changed from  to Thirty Seconds To Mars
.ItemStateChangedEvent] - Receiver_ImageURL changed from UNDEF to http://192.168.xxx.yyy/album_art.cgi
.ItemStateChangedEvent] - Receiver_Image changed from UNDEF to raw type (application/octet-stream): 76891 bytes
.ItemStateChangedEvent] - Receiver_Control changed from PAUSE to PLAY
.ItemStateChangedEvent] - Receiver_Time changed from --:--:--/--:--:-- to 00:00:01/00:01:58
.ItemStateChangedEvent] - Receiver_Time changed from 00:00:01/00:01:58 to 00:00:02/00:01:58
`

**Comment by Cossey** [comment]
> Unfortunately PaperUI doesn't show albumArt image:  image (broken image?)

Thanks for letting me know. There is a problem with the way the album art image is loaded. 

Okay, I've built the Binding for you to test, this should add support for your receiver and also fix the issue with the Album Art channel showing a broken image: [https://www.dropbox.com/s/rci4lzrbwu1tmfg/org.openhab.binding.onkyo-2.5.0-SNAPSHOT-txnr474.jar?dl=0]()

## How to use
* Remove your already added Onkyo Thing, if it's still there _from Paper UI **Configuration > Thing > Trash Icon**_
* Remove the Onkyo Binding that comes with openHAB _from Paper UI **Add-ons > Bindings > Remove Button**_
* Install this binding into the add-ons folder
* Give it a minute or two for openHAB to pick up the new binding and install it
* Do another scan _from Paper UI **Inbox > Refresh Button**_ it should then detect your receiver correctly
* Click the Tick button to add the binding
* Test and see how it works; you should also notice that the album art displays in _Paper UI_ when listening using the NET input.

**Please get back in touch with me if it works so that I can open a PR to get this added into openHAB. Cheers.**

**Comment by AlexKay88** [comment]
Wow, Stewart, that was quickly!
Downloaded and tested your snaphot:

- TX-NR474 identification works
- displaying albumArt works

Everything works like a charm!
**You made my day - many thanks!!!**

**Comment by Cossey** [comment]
I have submitted a Pull Request to add this receiver into the official openHAB Onkyo binding so it should be there in the next release, for now however you can just use the binding provided above. 

If you could please close this issue now, cheers.
