### ISSUE TITLE
[network] Improvements to detection of arping tool and debugging output

### ISSUE THREAD

**Issue by yuergen** [openhab/openhab2-addons#4494]
## Context
While adding presence detection based on the reachability of mobile phones to my openHAB instance, I noticed a few possibilities for improvement in the network binding. This is mostly because of the aggressive power saving mechanisms in current mobile phone operating systems, which seem to disable WiFi or parts of the network stack when in deep sleep for longer periods of time.

## Expected Behavior
- Basic diagnostic information for the binding and things in HABmin and PaperUI, e.g. is arping available.
- Extended debugging functionality via trace logging, e.g. giving indication when a device has been reached via arping ( issue #3514 )
- Usage of the timeout parameter in conjunction with -C for arping by Thomas Habets in versions later than 2.18. ( issue #3581 )

## Possible Solution
I will create a pull request with this issue ID shortly. I have added bits of documentation which go along with the changes in the code.

**Comment by longwa** [comment]
I've also been playing around with the exact same thing. I've noticed a few things that aren't really handled by the plugin at all.

Even after sending the UDP packet to "wake" the iphones, the ARP response is spotty at best. With the default version of arping on the openHabianPi installation, which is 2.14, it's much more reliable to send multiple packets quickly. Specifically, the iphones seems to take a bit to wake up and answer.

I'm using `arping -c 50 -W 0.05 -i eth0 ip_address` which will run 50 pings fairly quickly. Usually when phones are in a deep sleep, it will take about 20-30 before it responds. Luckily, this version of `arping` seems to return exitValue = 0 if there's at least 1 successful reply. This does, however, break the latency check so that would need to be separated into a call that only sends 1 packet after the device is found to be online. I didn't do that in my testing since I don't care about the latency channel right now.

The other problem, as noted by @yuergen  is the properties reported by the Things are not correct. Specifically, the arState flag is never set to anything other than Disabled in the case that `arping` is installed and working. I see a lot of confusion in forums about whether it's even being used for detection.

At minimum the block should be:
```
    public void setUseArpPing(boolean enable, String arpPingUtilPath) {
        this.arpPingUtilPath = arpPingUtilPath;
        if (!enable || StringUtils.isBlank(arpPingUtilPath)) {
            arpPingState = "Disabled";
            arpPingMethod = null;
        } else if (destination == null || !(destination instanceof Inet4Address)) {
            arpPingState = "Destination is IPv4";
            arpPingMethod = null;
        } else {
            arpPingState = "Enabled"; //This line is missing in the 2.4 version and "Disabled" is default
            arpPingMethod = networkUtils.determineNativeARPpingMethod(arpPingUtilPath);
        }
    }
```
