### ISSUE TITLE
[network] "latency" values do not show actual network latency

### ISSUE THREAD

**Issue by goligo** [openhab/openhab2-addons#4531]
I am using the network binding to monitor several devices in my local network. I noticed that the "latency" value returned by the network binding does not correspond to the actual ping time (when calling ping on the command line).

My devices do have ping times between 0.5ms (LAN) and 5ms (Wifi). The network binding returns random values between 8ms and 20ms regardless of LAN/Wifi. Looks like it does not parse the actual values from the ping response, but instead uses some own timer? 

It would be great if it would return the actual network ping time. I can also imagine additional configuration of to chose the number of pings to be done and whether I want to get the median or average value (or even both?).

I am running OpenHAB 2.4.0 on a Raspberry 3 B+, Network Binding 2.4.0.

**Comment by goligo** [comment]
Seriously? The binding is showing latency values which are wrong by a factor of 20 to 50, although correct values are returned by the external tool, but it is just not read. How does it improve consistency to compare opening a TCP connection from within Java with the overhead of starting an external binary from Java?

For the LAN the latency values are completely useless, as they are unrelated to the actual network latency.  As I understand the network binding, its purpose is monitoring of availability and latency of network devices in the LAN (maybe I am mistaken here?).

**Comment by davidgraeff** [comment]
It is correct that the binding does its own measurement. Mostly because we need to support 3 operating systems with different ping utility outputs. I would however accept a PR to "increase" the accuracy of our latency channel.

I do not see this as an Issue however because the network binding never promised in its documentation that the latency channel outputs pure network latency or application+network latency.
