### ISSUE TITLE
Skeleton scripts add wrong headers to generated code causing ParameterizedRegexpHeaderCheck errors

### ISSUE THREAD

**Issue by Jochen1980** [openhab/openhab2-addons#4637]
Generated comments created by create_openhab_binding_skeleton.sh lead to error in static code analysis, when calling mvn clean install to the newly created binding. I used the shell script on a OSX machine.

**Comment by martinvw** [comment]
Can you mention / quote the exact errors, this could help people working on it.

**Comment by Jochen1980** [comment]
I cannot quote the exact error message, but it was obivours for me, that you just need to change the comment of the first few lines to:

> /**
>  * Copyright (c) 2010-2019 Contributors to the openHAB project
>  *
>  * See the NOTICE file(s) distributed with this work for additional
>  * information.
>  *
>  * This program and the accompanying materials are made available under the
>  * terms of the Eclipse Public License 2.0 which is available at
>  * http://www.eclipse.org/legal/epl-2.0
>  *
>  * SPDX-License-Identifier: EPL-2.0
>  */

**Comment by martinvw** [comment]
Seems to be related to https://github.com/openhab/openhab2-addons/pull/4623

**Comment by Hilbrand** [comment]
The answer is yes and no is it related to #4623 :slightly_smiling_face: The problem of the copyright was already present (see #3158) as the script always generated the Eclipse Smart Home copyright. With the update of the copyright in openhab2-addons is still different than in the ESH copyright and therefor will still give the error.
Since the ESH will be integrated in openhab-core we will control the copyright text generated in the scripts and the generator will be updated too. Fixing this problem. The script generator will become part of openhab-core and the fix for this should be part of https://github.com/openhab/openhab-core/pull/467.

To fix this run in the root of your openhab2-addons code:
`mvn -pl :<binding artifactId> license:format`  (Don't forget the colon before the artifactid!)

**Comment by martinvw** [comment]
Great thanks!!

**Comment by wborn** [comment]
The workaround of manually applying `license:format` has been an issue for a while and is also part of the binding [implementation instructions](https://www.openhab.org/docs/developer/development/bindings.html#implement-the-binding).

**Comment by Jochen1980** [comment]
Thanks for your advice! I can see that there is a manual workaround. Anyway, how can I fix this issue? 

IMHO I need to know which file generates the comments and afterwards I need to test the changes, if all works fine. I am not able to see any more unwanted side effects ... fortunately I am right on this.

**Comment by Hilbrand** [comment]
You mean fixing the skeleton scripts that generate these files?

**Comment by Jochen1980** [comment]
Yes - exactly - I hope that I will be able to solve much more issues in future and I guess that could be a good start.

**Comment by Hilbrand** [comment]
The files are part of the maven plugin and is part of eclipse smart home. However, as you may know, ESH is being integrated into openHAB and part of that process is to move the build to a pure maven build. This process is currently done in https://github.com/openhab/openhab-core/pull/467. Part of it is to migrate the maven plugin also. However that work needs to be done (see the pr, files need to be put in `tools/archetype` again). But is planned to be done after the merge. So work on it can start when the pr is merged. If you will, you can work on it and also update the copyrights. Help is certainly appreciated. If you want to do this, post it on the pr before somebody else will pick it up. Otherwise you might do double work.

**Comment by davidgraeff** [comment]
Tracked with openhab/openhab-core#589
