### ISSUE TITLE
[mcp23017] Outdated documentation found by Google search

### ISSUE THREAD

**Issue by mrumpf** [openhab/openhab2-addons#4807]
When you do a Google search for "openhab MCP23017", the following 2 pages are returned at the top:
* https://www.openhab.org/addons/bindings/mcp230171/
* https://www.openhab.org/addons/bindings/mcp23017/

The first one seems to be an outdated OpenHab 1.x version of the page with a slightly different name.
This was confusing when I first used the old configuration format.

Please make sure that the old page is either marked clearly as OpenHAB 1.x or better remove it as there is no "MCP23017(1)" chip.

**Comment by Hilbrand** [comment]
Normally you should see such a warning on the page: see https://www.openhab.org/addons/bindings/dsmr1

I suspect the reason this is not the case here is because the openHAB 1 version of the binding is not part in any `feature.xml` in the openHAB1-addons repository. This also means it's not possible to install them. I noticed the same is for the max! binding.

The solution would be to either remove this binding from the openHAB 1 repository completely or add the binding to the legacy bindings.

The reason you see mcp23017**1** is that when a openHAB 1 binding is replaced by an openHAB 2 binding the convention is to add a **1** at the end. In this case that is confusing.

I'll see if I can transfer this issue to the openHAB1-addons repository as it is related to there.

**Comment by mrumpf** [comment]
OK, but in this case, the 1.x binding could have a warning at the top of the page similar to "This is the 1.x binding. In case you are looking for the 2.x version, follow *this* link.". This would avoid the confusion, caused by the naming issue.

**Comment by Hilbrand** [comment]
Yes that should have been the case. You should have seen that message, just like with the other binding I mentioned. That also contains a link to the new binding. But for some reason this message is not shown (And I suspect this is related to the feature.xml I mentioned, I've created a issue for it in the openHAB1-addons repository).

**Comment by davidgraeff** [comment]
Because this is a documentation generator problem and there is an open issue now, I'm closing this.
