### ISSUE TITLE
[meteoblue] Image-Channel "Icon" state NULL

### ISSUE THREAD

**Issue by michaeljoos72** [openhab/openhab2-addons#4924]
I tried to use the weather binding for meteoblue free account. According Docu:

Icon | Image | Image used to represent the forecast (calculated)

I don't know how this is exactly implemented (calculated), but my Item always keeps state "NULL". There is another user that did ask this and it seems that it doesn't work:
https://community.openhab.org/t/new-meteoblue-binding-no-icon/66143

I'm on latest snapshot 1524.

**Comment by 9037568** [comment]
Working fine here:

![image](https://user-images.githubusercontent.com/9916473/52987704-3f4e0980-33ca-11e9-9848-0714fece0030.png)

Suggest you try the stable release, and if you still have an issue, don't ignore the information requested when submitting an issue.

**Comment by michaeljoos72** [comment]
OK, agree. But user Rene did mention in the community that he is using 2.4 and he has the same issue.
Maybe we both missed something? From where exactly is this image coming? Is it a link to an external site or do we have to save icons in the html-folder?

Most probably we have to continue the discussion there:
https://community.openhab.org/t/new-meteoblue-binding-no-icon/66143

**Comment by Gardener74** [comment]
Gentlemen, I successfully installed the meteoblue binding with the latest stable version of OH 2.4.0. I downloaded all images from meteoblue as instructed, renamed the png files to e.g. "day-1.png", uploaded those 19 files from the png download to the openhab folder conf/icons/classic but still no image shown. What do I do wrong? There is simply no content.

**Comment by Schnuecks** [comment]
Sorry for hijacking this issue.
But i use current version 2.5.0 and the current meteo binding 2.5.0 

All data from meteoblue is correctly shown instead of the current condition icon

i renamed the meteoblue files like day-1.svg iday-1.svg night-1.svg and so on.
all stored in /etc/openhab2/icons/classic and owned by openhab

Chrome 
Failed to load resource: the server responded with a status of 404 (Not Found)
http://myopenhab:8080/icon/iday?state=3&format=svg&anyFormat=true

Jetty 
HTTP ERROR 404
Problem accessing /icon/iday. Reason:

    Not Found
Powered by Jetty:// 9.4.20.v20190813

How must the correct filenames for the icons?

Could anyone help here. Thanks
