### ISSUE TITLE
[modbus] Confusing migration scenario

### ISSUE THREAD

**Issue by skazi0** [openhab/openhab2-addons#4930]
The documentation at https://www.openhab.org/addons/bindings/modbus/#how-to-manually-migrate takes input with four slaves, each with different `id` and transforms that into one bridge with `id=1`. The doc states that only one device is addressed so one top level bridge is needed.

As far as I understand, the `id` in 1.x configuration defines one slave device (unit) on a bus addressed with `address`. This means that actually there are four top level bridges needed to cover the same configuration.

Can someone please verify and/or update this section of the docs?

**Comment by Rossko57** [comment]
Correct observation.  I think the example is in error, and all the "1.x" slaves were intended to have the same ID number.

**Comment by wborn** [comment]
Perhaps @Wolfgang1966 or @ssalonen can create a PR to make the migration documentation less confusing? The migration documentation was added in #4555.

**Comment by Wolfgang1966** [comment]
Hi all,

the 1.x configuration in this example was taken from my real existing openhab configuration and used 4 different ids. As far as I uderstand https://www.openhab.org/addons/bindings/modbus1/#global-configuration, different slave ids are mandatory even if the slaves addressed the same physical device. This is because the item configuration refers the slave id and uses relative addresses within those slaves. @ssalonen, please correct me if I'm wrong here. If I would have used the same id number there, item definitions could not distinguish between e.g. holding 3 of slave 2 and slave 3. Two slaves here were e.g. necessary because of the limited packet length of modbus, 128 byte IIRC.

The 2.x modbus binding now distinguishes between the target device (top level) and the address ranges and data types polled within this device. Again, the configuration in the documentation is the configuration I now run in my openhab instance. It may be possible to define 4 top level bridges for this constellation and get a running configuration. I never tried this, as I think this is not what @ssalonen intended. At least I can tell for sure that it is not mandatory.

I only have one modbus target at home. So if anybody has a two target configuration, of course the documentation could made be more clear by showing also how to deal with that kind of setup.

I hope that helps to clarify the situation a little bit. If not, feel free to ask for more details.

Yours

Wolfgang

**Comment by ssalonen** [comment]
@Wolfgang1966  I think you mixed two concepts. In the old binding there are

- `<slave-name>` : name of the "virtual slave" -- this is used in item definitions to refer to the data
- `id` parameter: concept in modbus protocol (see e.g. [here](http://www.simplymodbus.ca/TCP.htm)). The `id` is passed in modbus requests. In some cases the `id` matter, in some cases it does not -- depends on your devices, really. Usually with TCP devices it does not matter.

It is OK to have many top-level bridges -- in fact, you do need to introduce top-level `tcp` or `serial` when the unit id is different.

Does this make sense?

**Comment by Wolfgang1966** [comment]
Hi all,

thanks for the clarification, now I got it (hopefully :-) ).

If I understand correctly, It would also be possible to remove the id value totally. Am I right?

If I am, that would be my preferred solution.

I create a PR for that.

Yours

Wolfgang

**Comment by ssalonen** [comment]
Yes you can remove `id` since it is optional parameter. It defaults to `1` in both binding versions.
