### ISSUE TITLE
[basic ui] Missing "Color Circle"

### ISSUE THREAD

**Issue by michaeljoos72** [openhab/openhab2-addons#4981]
The color background (circle) for a dimmer-item is missing in Basic-UI:

![image](https://user-images.githubusercontent.com/20517474/53290798-772dc600-37a9-11e9-89b2-e268268d60c2.png)

openHAB Snapshot 1533
binding-hue - 2.5.0.SNAPSHOT

**Comment by wborn** [comment]
Did you also try using a `Color` item instead of a `Dimmer` item? That's the item type normally used with a `Colorpicker` in the sitemap.

If you don't have a color light you can also use a `Slider` on the sitemap with a `Dimmer` item.

See also the [element types](https://www.openhab.org/docs/configuration/sitemaps.html#element-types) documentation.

**Comment by michaeljoos72** [comment]
Ahhh, sorry my mistake....sure, it's already a color item:

`Color Light_Sofa_Dimmer "Sofa" <colorlight> {channel="hue:0210:001788215d9c:1:color"}`
`Colorpicker item=Light_Sofa_Dimmer`

**Comment by wborn** [comment]
Looks like a bug in Basic UI since it also occurs with the Demo:

![demo](https://user-images.githubusercontent.com/12213581/53297931-2314f700-3826-11e9-8a17-733116868177.png)

The console shows a few 404s:

```
colorwheel.png:1 GET http://localhost:8080/basicui/images/colorwheel.png 404 (Not Found)
colorpicker-thumb.png:1 GET http://localhost:8080/basicui/images/colorpicker-thumb.png 404 (Not Found)
```

Can you transfer this issue to the webui repo @kaikreuzer ?

**Comment by wborn** [comment]
The images were just missing see https://github.com/openhab/openhab-webui/pull/23.
