### ISSUE TITLE
Repo GH permissions

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab2-addons#5067]
I am not a maintainer, or TMK even a contributor, but for some reason I appear to have more permissions than I should in this repo. Maybe it's just me... maybe everyone? I just closed an issue, and it looks like I might be able to merge!

@openhab/2-x-add-ons-maintainers

**Comment by martinvw** [comment]
@kaikreuzer could you look into this?

**Comment by kaikreuzer** [comment]
Everyone of the https://github.com/orgs/openhab/teams/contributors team has write access to the repo, which includes the right to close issues. We require this to be able to use the CODEOWNERS file, because this mechanism does not work for people without write access.

> and it looks like I might be able to merge!

We have protected the master branch and require at least one approval from a maintainer - so unless such an approval is already available on a PR, my expectation would be that you actually cannot merge PRs. Can you confirm?

**Comment by openhab-5iver** [comment]
Confirmed... I cannot merge PRs without approvals. I was only recently added to /teams/contributors, so that explains why things look different for this repo. Just wanted to make sure it was intentional. Thank you!
