### ISSUE TITLE
Crowdin in general and for openweathermap binding

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#5069]
When I open Crowdin, for openhab2-addons, the only binding that appears is openweathermap.
Is it expected to not have other bindings ?
When I enter in openweathermap, I don't find the file openweathermap_fr.properties, while this file is already existing in Git. Is there something wrong or not ?

**Comment by cweitkamp** [comment]
We never started a real translation campaign for openHAB Add-ons. The OWM project was (or even is) a test subject from myself to get an idea of how it is working. All existing translations for the OWM binding were introduced the "old" way by submitting a PR to the target repository. Because of that the FR properties file is not existing over there. One of our next steps is the switch the build to maven + bnd which will bring a change in the repository structure. After that we can think about setting up a proper Crowdin project for this repository.

If you like to help it will be appreciated. You may want to ask @kaikreuzer for granting you rights in Crowdin or you may want to start with a private project first (see https://github.com/openhab/openhab-core/issues/275 for further information).

**Comment by lolodomo** [comment]
Ok, so I can continue pushing PR with the old method to add translations to bindings ?

**Comment by cweitkamp** [comment]
Yes, you can.

**Comment by lolodomo** [comment]
Thank you for the information.
