### ISSUE TITLE
Question: Does an extensionservice belong in here or openhab-core?

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab2-addons#5110]
Does an extensionservice belong in here or openhab-core?

Background: I find it still highly confusing where to draw the line between the core and the addons repo.

My gut feeling is that extension services should go into the core or the distro repo.
They are no classic openhab addons, but allow to discover further addons.

The eclipse marketplace is in this repo though.

My extensionservice is for allowing openhab-web-uis to be installed from the node-package-manager registry (npm-js).

Thanks, David

**Comment by davidgraeff** [comment]
@openhab/2-x-add-ons-maintainers

**Comment by wborn** [comment]
I can imagine it's currently in openhab2-addons because the ESH IoT Marketplace will no longer exist in the future. So it might be here to prevent solutions building upon openhab-core from using the Marketplace.

**Comment by kaikreuzer** [comment]
The extension service interface had been created because the one existing extension was openHAB specific and thus couldn't be part of ESH.

I am not convinced that we need a general "extension service" add-on type (similar to bindings, persistence services, etc.) at all, so that's probably why it isn't in openhab2-addons.
As @wborn says, the Eclipse Marketplace integration will have to be removed, so we should imho mainly think about ONE official way how external add-ons can be hooked into openHAB - we had discussed a separate github repo with the required metadata in the past.
