### ISSUE TITLE
Travis builds time out 

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab2-addons#5468]
Since the karaf upgrade to 4.2.4 Travis fails in nearly all builds. Build is quite quick but feature verification takes too much time.

I tried downgrading karaf in addons to 4.2.1 or upgrading karaf-maven-plugin to 4.2.4 but neither did help.

**Comment by wborn** [comment]
I've seen such [timeouts happen](https://travis-ci.org/openhab/openhab2-addons/builds/514709371?utm_source=github_status&utm_medium=notification) a few weeks ago already. For some reason it's sometimes slow. Maybe it's also due to downloads taking longer? There have been several builds of the master that were [successful](https://github.com/openhab/openhab2-addons/commits/master) after Karaf was updated to 4.2.4.

**Comment by kaikreuzer** [comment]
On Jenkins, the times do not show any unexpected changes since the 4.2.4 upgrade: https://ci.openhab.org/job/PR-openHAB2-Addons/buildTimeTrend

**Comment by wborn** [comment]
[This recent PR build](https://travis-ci.org/openhab/openhab2-addons/builds/520949676) was completed by Travis in 32 minutes. :hourglass_flowing_sand: :clock1030:

**Comment by J-N-K** [comment]
Closing this for now.

**Comment by wborn** [comment]
I also contacted Travis support if there were any known issues causing  slowdowns.
There weren't any and there wasn't anything unusual with our build setup.
To prevent future issues, they've increased the build timeout for this project to 90 minutes. :+1:

**Comment by J-N-K** [comment]
Thats Great news!

**Comment by J-N-K** [comment]
Do you think we can re-enable tests for Travis?
