### ISSUE TITLE
[loxone] Tag Rollershutter

### ISSUE THREAD

**Issue by Tihmann** [openhab/openhab2-addons#5615]
Is it possible to user the [Blinds] tag instead of [Rollershutter] tag, so that those items are exported to Google Assistant - it only works with [Blinds]

**Comment by ppieczul** [comment]
@tihmann Yes it is easily possible. Which channels of the control should be tagged so it works fine? Can all be tagged? Thanks.

**Comment by Tihmann** [comment]
@ppieczul yes all channels should and can be tagged with the [Blinds] tag. That would be very helpfull. Thanks.

**Comment by Tihmann** [comment]
@ppieczul It would be really helpfull as the channels would be exported to Google Home.

**Comment by ppieczul** [comment]
@Tihmann I can't get an IDE setup to work for the development. As soon as it is usable (or I find out what I am doing wrong), I will add them.

**Comment by ppieczul** [comment]
@Tihmann I made the changes. Would you be able to give it a test? Here is a jar: https://www.dropbox.com/s/t47d2ce3w5ly1to/org.openhab.binding.loxone-2.5.0-SNAPSHOT.jar?dl=0

**Comment by Tihmann** [comment]
@ppieczul Thank you very much. I just installed the new jar. Not able to test at the moment as myopenhab.org is down...
Habmin shows Blinds as tag. I will follow up and give feedback here

**Comment by Tihmann** [comment]
As myopenhab.org is online again, I was able to test it. Works like a charm, thank you very much.

**Comment by ppieczul** [comment]
Great. I will submit it for review and merge.

**Comment by Tihmann** [comment]
@ppieczul Loxone adds 3 channels for each rollershutter: the rollershutter itself, shade and auto shade. Shade and auto shade are tagged as switches. 
The only question is if you want to tag both switches (shade and auto shade) as blinds as well. For my use case tagging the rollershutter itself as blinds would be enough. Maybe it would be more logical if we just leave the switches as switches so it doesn interfere with other usecases ?

**Comment by Tihmann** [comment]
@ppieczul I just did some research and found this: https://www.openhab.org/docs/ecosystem/google-assistant/. So maybe it would be more logical to tag shade and auto-shade with ["Switchable"] ?

**Comment by ppieczul** [comment]
@Tihmann Great. I added more tags according to this document:
- Switch and derived classes (Pushbutton, TimedSwitch) - when category is lights, tag is Lighting, otherwise Switchable
- Dimmer - when category is lights, tag is Lighting
- Light Controllers - tag is Scene for the main channel with scene number
- Rollershutter - tag is Blinds for the main channel and Switchable for other channels

I also added a configuration option to disable automatic tagging. This may actually require to remove the thing and add it again to make this option show in the thing configuration.

Would that make sense? 

Here is a test jar with these changes: https://www.dropbox.com/s/p1zunvigxui1q3e/org.openhab.binding.loxone-2.5.0-SNAPSHOT-2.jar?dl=0

I did not manage to test it under IDE and did not install on my setup yet, just wrote new unit tests for tags. If you can, please give it a try.

Thanks

**Comment by Tihmann** [comment]
I just installed the new version. Rollershutter work as described. Switch work as described. I have to check for light controllers. I don have any dimmers installed, so I can verify that

**Comment by Tihmann** [comment]
configuration option in the IDE did work without deleting the thing

**Comment by ppieczul** [comment]
May be closed now as #5756 is merged.
