### ISSUE TITLE
[infrastructure] Remove all .project and .classpath files (OH3)

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab2-addons#5670]
Because we support multiple IDEs now, removing Eclipse specific files makes sense for OH3

**Comment by kaikreuzer** [comment]
I can only be convinced that they should be removed if I am shown an (automatic) Eclipse IDE setup that doesn't work worse than before the change...

**Comment by tmrobert8** [comment]
Additional note here - vscode's java extension also uses these files...

**Comment by lucacalcaterra** [comment]
I'm preparing a new branch for a pull request of my new binding... Using the Java extension VS code when fork and clone the openhab2-addons repo Vscode create a .classpath file on every binding. How manage them without have a dirty repo ?

**Comment by lucacalcaterra** [comment]
ps on root .gitignore only .factorypath is ignored.

**Comment by lucacalcaterra** [comment]
I noticed that VSCode auto build all bindings , changing .classpath in every binding. 

I must disable it ?

**Comment by kaikreuzer** [comment]
I'd consider VSCode support for development to be only experimental for now.
We will keep the .classpath files in the repo and they should not be (semantically) changed. If VSCode can be configured in some way to accept them as they are, it would be best.

**Comment by tmrobert8** [comment]
@kaikreuzer @lucacalcaterra 

The VSCode java language extension (by redhat) will, by default, will work with .classpath, .project and .factorypath.  All of those are compatible with Eclipse.  

The issue is - the java extension will CREATE those if they are not found - including any directories that don't have them in the build path (here's the issue request to prevent that:  https://github.com/redhat-developer/vscode-java/issues/618) and there seems to be no way of turning that off for now (until that issue is addressed).

The best thing to do, for now, is to simply revert those other files when you are about to commit (or don't stage them).

The other option (which this now closed issue was about) is to remove all the classpath/projects and add those to the gitignore - then this wouldn't be an issue either.

.  I added '.factorypath' to the gitignore since we weren't using them before

**Comment by lucacalcaterra** [comment]
Infact i would bypass the issue adding those files in gitignore, but not
know if are issues with pull request after.

At the end, it's better use vscode or eclipse on binding development ?

Il giorno gio 27 giu 2019 alle ore 13:16 tmrobert8 <notifications@github.com>
ha scritto:

**Comment by tmrobert8** [comment]
Ultimately it's up to you - I personally have switched fully over to vscode.   It's fast and is just easier to work with then eclipse and it has just about the right number of refactorings for me.  However, there are two big downsides:
1. No real time null annotation analysis - you'll only get those when you build
2. Still Missing a few addons that I liked (autodocing, findbugs, etc)

However, the pure speed, ease of use and it actually works are the big pulls for me..

**Comment by lucacalcaterra** [comment]
Ok, thanks for all suggestions !

I prefer vscode too... probably still young ide but very powerful!
