### ISSUE TITLE
[gardena] value of signal strength items is incorrect

### ISSUE THREAD

**Issue by birnstingl** [openhab/openhab2-addons#5747]
I am using gardena binding with 4 devices (2x water control, 1 sensor and 1 mover)
signal strength values for all devices is either 1 or 2 although actual values are between 30%-70%
and the values are not shown as % but just as plain numbers
![openHAB](https://user-images.githubusercontent.com/52003333/59779407-7e2c9700-92b8-11e9-9d5a-42dc7670eef7.jpg)

**Comment by wborn** [comment]
Because signal strength can be expressed in multiple ways (percentages/numbers), in openHAB/ESH all signal-strength channel types use a standardized 0-4 interval, see [System State Channel Types](https://www.eclipse.org/smarthome/documentation/development/bindings/thing-definition.html#system-state-channel-types):

> Represents signal strength of a device as a Number with values 0, 1, 2, 3 or 4; 0 being worst strength and 4 being best strength.
