### ISSUE TITLE
Unable to get and put data from plug enocean

### ISSUE THREAD

**Issue by jrcourtois** [openhab/openhab2-addons#643]
I got a plug which device reference type is W1R16FP.

And I don't manage to retrieve the consumption from this device, I don't know where else I could ask to know if this is supposed to be managed in some way or not.

**Comment by kaikreuzer** [comment]
As there is no enocean binding in openhab2-addons, shouldn't this issue rather to go https://github.com/openhab/openhab/issues?

**Comment by jrcourtois** [comment]
OK, as I managed to install it through the Paper UI I thought it was in openhab 2...

**Comment by kaikreuzer** [comment]
No worries, it is not always easy to spot where it should go, that's why I am redirecting you :-)
This repo here (openhab2-addons) now specifically only contains 2.0 add-ons. The whole runtime distribution (which also packages stuff from openHAB 1 and Eclipse SmartHome) has moved to https://github.com/openhab/openhab-distro.
