### ISSUE TITLE
Where have the icons gone?

### ISSUE THREAD

**Issue by reitermarkus** [openhab/openhab2-addons#667]
Hi,

it's been quite a while since I added my icon set. I'm currently designing some new icons and have been looking all over the place to find where they are located now.

Apparently they were removed in https://github.com/openhab/openhab2-addons/pull/601. I couldn't find any info on where they were moved, did I miss something?

**Comment by kaikreuzer** [comment]
Hi Markus!
The ended up [here](https://github.com/kaikreuzer/openhab-core/tree/master/bundles/org.openhab.ui.iconset.classic/icons), but this is only a temporary location.
What I would like to do with you is to move this "classic iconset" bundle to Eclipse SmartHome, a bundle for it [already exists](https://github.com/eclipse/smarthome/tree/master/extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic).
To do so, we would need to find the best matching icons for the different [channel categories](https://www.eclipse.org/smarthome/documentation/development/bindings/thing-definition.html#channel-categories), because any iconset should provide icons for them. Is this something you could have a look at?

**Comment by reitermarkus** [comment]
Sure, I'll take a look at it. https://github.com/kaikreuzer/openhab-core/issues/21

**Comment by kaikreuzer** [comment]
Cool, thanks!
