### ISSUE TITLE
Hue Emulation (Amazon Echo) Problem - Address already in use

### ISSUE THREAD

**Issue by DigitalBites** [openhab/openhab2-addons#698]
When there are other plugins that are using UPNP discovery i'm getting an error that the hue emulation plugin is unable to bind to my network adapter because "the address is already in use". 

You can only have one service at a time using a IP/Port combo and in my case with the wemo plug-in PLUS this one, first one in wins and the second gets an error. I believe the version of the wemo plugin is using the UPNP framework that is part of openHAB which means it only opens up one process that uses the port (listens for connections) 1900 but i've not looked at the code for this yet.

It appears on line 90 of HueEmulationUpnpServer.java there is a completely separate and new instance of a UPNP server and this is causing the conflict.

**Comment by kaikreuzer** [comment]
This is indeed a problem that escaped me.
@digitaldan I think it would make sense to refactor this part.
You should have a look at how you can register yourself as a service on jUPnP instead (maybe by adding some new features to https://github.com/eclipse/smarthome/tree/master/bundles/io/org.eclipse.smarthome.io.transport.upnp first).

**Comment by digitaldan** [comment]
Yep, I don't know why I thought to due this myself,  it might have been influenced from the non standard discovery stuff in the Harmony binding I was writing at the same time.  I would much rather use the built in upnp functionality.  I'll look at it soon.

**Comment by digitaldan** [comment]
Now I remember why , it's amazing how quickly I forget things ;-)  We need to support device advertisement as opposed to device discovery which is how we use upnp today.  Looking at the jupnp/cling docs this should not be hard to implement.

**Comment by kaikreuzer** [comment]
Yes, it is the other direction, which nobody used in ESH/OH2 before, but which should be in general supported by jUPnP/Cling - looking forward to your results, good luck :-)

**Comment by DigitalBites** [comment]
Aside from this the plug in worked flawless for me. I can't wait to use it more!

**Comment by digitaldan** [comment]
see #705

**Comment by digitaldan** [comment]
@DigitalBites that's great, thanks!

**Comment by digitaldan** [comment]
@kaikreuzer so I'm a little stuck with jupnp.  The Hue needs a URLBase field in the device description file, unfortunately this was removed from jupnp, see https://github.com/jupnp/jupnp/blob/master/bundles/org.jupnp/src/main/java/org/jupnp/binding/xml/UDA10DeviceDescriptorBinderImpl.java#L414

So, this leads me to believe I will need to handle the advertising myself.  I was mostly concerned about 2 things with this approach

First was that I was exclusively binding to a port the jupnp sdk needed to function.  Learning from you however that multicast binds are not exclusive removes this concern.

Second was the conflict with the WeMo binding since this was what was causing the issue raised in this bug.  That has been fixed in the WeMo binding (Feb 25th) and is no longer a concern.

What I would like to do is keep the structure, but have the binding respond on a random port (not 1901).  This is too avoid any conflict with jupnp trying to use the non multicast version of this port. Also binding to a random port is preferable if possible to avoid future conflicts, there was no good reason for me to pick 1901 I'm not sure what influenced me to do that. 

I saw your name on least least one jupnp file so I know who to ask for help next time!

**Comment by hmerk** [comment]
@digitaldan 
did you already try if the emulated bridge is discovered if you leave the URLBase.
I am saking, cause WeMo devices don't use URLBase in the descriptor, but are discovered correct by my Echo/Alexa.

**Comment by digitaldan** [comment]
> did you already try if the emulated bridge is discovered if you leave the URLBase.
I am asking, cause WeMo devices don't use URLBase in the descriptor, but are discovered correct by my Echo/Alexa.

@hmerk unfortunately the base URL is required for hue bridges. 

> I just had a closer look at the descriptor.xml of the HUE bridge, which shows, that it is a UPnP V1.0 compliant device, therefore, use of URLbase should be allowed.
It might be possible to extend UDA10DeviceDescriptorBinderImpl.java to allow using of URLbase if a minor version of "0" is used.

That's good to know, thanks for looking that up.  Hopefully the current solution will work as it's already committed into OH2.  If not I will have to try that option. 

@kaikreuzer should we close this issue? I think #717 solves this.

**Comment by kaikreuzer** [comment]
Yes, sure! Thanks :-)
