### ISSUE TITLE
Consistent bundle naming

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2-addons#765]
This is rather a suggestion to rename all bundle identifiers so that the show up in a consistent way when issuing a bundle:list command on the Karaf command line, e.g.

Astro Binding -> openHAB 2.0 Astro Binding

and in a similar way, prepend "openHAB 1.x" for the OH1 bindings, in a similar way to the "Eclipse Smarthome" prefix on all bundles
##

**Comment by kaikreuzer** [comment]
I would not add the version to the binding name, since the version is anyhow displayed for each bundle.

So I would go for a simple "openHAB" prefix.

**Comment by kgoderis** [comment]
Shall we then rename them all at the next occasion?

**Comment by kaikreuzer** [comment]
Feel free to create a PR!

**Comment by lolodomo** [comment]
It will require a change of all MANIFEST.INF ?
What about the name in binding.xml ?

**Comment by kaikreuzer** [comment]
Sorry, I think this was a bit pre-mature. Note that the bundle symbolic name is created by [the archetype](https://github.com/eclipse/smarthome/tree/master/tools/archetype/binding/src/main/resources/archetype-resources), for which we would need an update as well. Furthermore, we have 40+ binding PRs in the queue, which all have the current naming scheme and merging them will again create a huge mess.
Not sure if this issue is worth all this effort?
After all, I usually always use a `bundle:list -s", which in any case looks much better and is more precise.

**Comment by lolodomo** [comment]
@kaikreuzer : you said (elsewhere) that the normal naming is without a prefix.
But the current situation is the following:
* OH 1.x bindings have a prefix "openHAB" in their bundle name
* OH 2 bindings have no prefix in their bundle name
* Eclipse SmartHome bindings have sometimes no prefix or sometimes the prefix "Eclipse SmartHome" in their bundle name
For me, there is no consistency.

**Comment by davidgraeff** [comment]
The names are in the process of being unified with the migration to bnd. Closing this now.
